### DISCUSSION TITLE
Troubleshooting connection Issue: Is telnet the right tool to diagnose?

### DISCUSSION THREAD

**Discussion by LazarenkoA** [apernet/hysteria#1053] [General]
After starting a systemctl unit on the server, I see the log entry `server up and running {"listen": ":443"}`. 
However, I can't connect as a client, even when attempting to use telnet from the client side. When I try `telnet 127.0.0.1 443` directly on the server, I get `telnet: connect to address 127.0.0.1: Connection refused`. Is this the expected behavior, or should telnet establish a connection? If not, how can I verify that the application is listening on the port, and determine if the issue lies within the virtual machine?

**Comment by haruue** [comment]
No, telnet is not the right tool for diagnosis.

Telnet uses TCP while Hysteria uses UDP. They are completely different things.

I've written a guide to test UDP connectivity with `socat`, but it's only in hy1's documents: https://v1.hysteria.network/docs/common-problems/#erro-errortimeout-no-recent-network-activity

**Reply by LazarenkoA** [reply]
@haruue tried to implement the recommendations with `socat`, it's works, but it's not possible to connect to the hysteria server, the error is `{"error": "connect error: timeout: no recent network activity"}`

**Reply by LazarenkoA** [reply]
![image](https://github.com/apernet/hysteria/assets/15386101/65799ee0-2a71-4b0e-8ac3-e10126c5b469)

**Reply by LazarenkoA** [reply]
![image](https://github.com/apernet/hysteria/assets/15386101/0ab4c70a-a749-44a4-a0d1-f7da762aef80)

**Reply by haruue** [reply]
Hello, the client config seems fine. Could you please show us your server config?

**Reply by LazarenkoA** [reply]
```
listen: :36713

tls:
  cert: /etc/hysteria/hysteria.server.crt
  key: /etc/hysteria/hysteria.server.key

auth:
  type: password
  password: ******

masquerade:
  type: proxy
  proxy:
    url: https://news.ycombinator.com/
    rewriteHost: true
```
