### DISCUSSION TITLE
请求帮助，hysteria2配置了acl，但是一直不生效。

### DISCUSSION THREAD

**Discussion by Elda1994** [apernet/hysteria#1204] [Q&A]
请求帮助，网络搜索了很久一直未找到解决办法。我vps搭建了hysteria2，按照官方文档配置，连接是正常的。我的vps安装了warp，并开启了warp的proxy模式。我通过配置acl，想达到特定域名通过warp proxy模式去连接网络，以此来解锁chatgpt，但是acl配置好了后，一直不生效。下面是我的配置文件：

```yaml
listen: :1443

acme:
  domains:
    - mydomain.xyz
  email: domain@gmail.com

auth:
  type: userpass
  userpass:
    user1: user1pass
    user2: user2oass

masquerade:
  type: proxy
  proxy:
    url: https://mydomain.xyz/
    rewriteHost: true

sniff:
  enable: true
  timeout: 2s
  rewriteDomain: false
  tcpPorts: 80,443,8000-9000
  udpPorts: all

outbounds:
  - name: v4_only
    type: direct
    direct:
      mode: 4
  - name: socks5_only
    type: socks5
    socks5:
      addr: 127.0.0.1:40000

acl:
  inline:
   - v4_only(suffix:google.com)
   - v4_only(suffix:x.com)
   - socks5_only(ios.chat.openai.com)
   - socks5_only(ip.sb)
   - socks5_only(android.chat.openai.com)
   - socks5_only(suffix:openai.com)
   - reject(geoip:cn)
   - reject(geoip:kp)
   - direct(all)
```

上面是我的配置文件，这个配置文件连接是正常的，但是当我登录ip.sb网站后，网站还是用我vps的ip去登录的，并没有通过warp proxy模式。同时手端也无法解锁chatgpt。vps端的warp连接是正常的。
请求帮忙。
