### DISCUSSION TITLE
Clash.Meta配置hysteria

### DISCUSSION THREAD

**Discussion by djwjb** [apernet/hysteria#389] [General]
最简单的
```
{
  "server": "example.com:36712",
  "obfs": "fuck me till the daylight",
  "up_mbps": 10,
  "down_mbps": 50,
  "socks5": {
    "listen": "127.0.0.1:1080"
  },
  "http": {
    "listen": "127.0.0.1:7890"
  }
}
```
config.json转换config.yaml：

```
port: 7890
socks-port: 1080

proxies:
  - name: "hysteria"
    type: hysteria
    server: example.com
    port: 36712
    obfs: fuck me till the daylight
    up: 10
    down: 50
    
proxy-groups:
  - name: PROXY 
    type: select
    proxies:
      - hysteria
      
      
rules:
  - MATCH,PROXY

```

**Comment by djwjb** [comment]
过滤本地
```
port: 7890
socks-port: 1080

proxies:
  - name: "hysteria"
    type: hysteria
    server: example.com
    port: 36712
    obfs: fuck me till the daylight
    up: 10
    down: 50
    
proxy-groups:
  - name: PROXY 
    type: select
    proxies:
      - hysteria
      
      
rules:
  - DOMAIN-SUFFIX,bilibili.com,DIRECT,tcp
  - DOMAIN,google.com,PROXY
  - DOMAIN-KEYWORD,baidu,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - SRC-IP-CIDR,192.168.0.0/16,DIRECT
  - DST-PORT,3389/445,DIRECT
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,icloud@cn,DIRECT
  - GEOSITE,apple@cn,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,geolocation-cn,DIRECT
  - GEOSITE,geolocation-!cn,PROXY
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,cn,DIRECT

  - MATCH,PROXY
```

**Reply by ferstar** [reply]
其实 server 写成真实 IP，然后增加 sni 信息会更好，省点每次重连对 server 的 DNS 查询时间

```yaml
proxies:
  - name: "hysteria"
    type: hysteria
    server: 1.2.3.4
    sni: example.com
    port: 36712
    obfs: fuck me till the daylight
    up: 10
    down: 50
```
