### DISCUSSION TITLE
Hysteria 2 服务端配置 masquerade 参数的 url 网址是否必须为支持 QUIC 的网址？

### DISCUSSION THREAD

**Discussion by chika0801** [apernet/hysteria#632] [Q&A] [answered]
```
masquerade:
  type: proxy
  proxy:
    url: https://some.site.net
    rewriteHost: true
```

https://some.site.net 这个转发的网站，是否应该必须找支持QUIC的？
