### DISCUSSION TITLE
Hysteria 2 服务端配置 对外监听能否只监听IPv4地址？

### DISCUSSION THREAD

**Discussion by chika0801** [apernet/hysteria#636] [Q&A] [answered]
这是我的服务端配置，我问过GPT，没有正确的方法。我用下面的配置后使用 ss -tunlp 命令查看端口，显示的是， *:443 是表示同时监听V4和V6吧。请问有这样设置的方法吗？

`udp                UNCONN              0                   0                                              *:443                                          *:*                  users:(("hysteria",pid=25739,fd=3)) `

```
listen: "0.0.0.0:443"

tls:
  cert: fullchain.cer
  key: private.key

quic:
  initStreamReceiveWindow: 16777216
  maxStreamReceiveWindow: 16777216
  initConnReceiveWindow: 33554432
  maxConnReceiveWindow: 33554432
  maxIdleTimeout: 5s
  maxIncomingStreams: 4096

auth:
  type: password
  password: chika

masquerade:
  type: proxy
  proxy:
    url: https://http3check.net
    rewriteHost: true
```
