### DISCUSSION TITLE
[Hysteria 2] HTTP/3 Check Fail

### DISCUSSION THREAD

**Discussion by gsuns** [apernet/hysteria#867] [Q&A] [answered]
你好
搭建好HY之后,代理可以正常工作.配置HY只监听UDP 443.伪装使用本地静态文件
但我使用 https://http3check.net/ 检测HY HTTP3功能时,发现失败了

![CCc9Sp6uPC](https://github.com/apernet/hysteria/assets/102716813/f47d3338-2b6c-4450-a60a-7f53981797fc)
所以......我想知道,HY就是这样,还是我的配置问题.
以下是我服务端配置
```
# listen: :443

tls:
  cert: /etc/hysteria/fullchain.pem
  key: /etc/hysteria/privkey.pem

auth:
  type: password
  password: aabbccddeeff

masquerade:
  type: file
  file:
    dir: /site/public/
```

**Comment by gsuns** [comment]
还有个问题,如何给 Hysteria 2 设置可以访问证书的权限.我的证书使用cerbot申请,路径是` /etc/letsencrypt/live/www.demo.com/ `,如果我把 Hysteria 2 证书路径直接设置Cerbot的证书路径. Hysteria 2 会报错 TLS.目前我只能把 证书放在 ` /etc/hysteria/ `目录下

**Comment by tobyxdd** [comment, marked as answer]
这个网站好像会先发起 TCP 请求，不支持只有 HTTP/3 的服务器。可以打开 [HTTP/HTTPS 伪装](https://hysteria.network/zh/docs/advanced/Full-Server-Config/#httphttps) 再试。

**Comment by gsuns** [comment]
> 這個網站好像會先發起 TCP 請求，不支援只有 HTTP/3 的伺服器。可以打開 [HTTP/HTTPS 偽裝](https://hysteria.network/zh/docs/advanced/Full-Server-Config/#httphttps) 再試。

大大 你是对的,HTTP/3 检测成功.
感谢指点,祝你生活愉快,身体健康. 

![O7EG25wTvt](https://github.com/apernet/hysteria/assets/102716813/831cdea0-4e23-44cb-b0e2-a473228ee4db)

附上我的配置

```
# listen: :443

tls:
  cert: /etc/hysteria/fullchain.pem
  key: /etc/hysteria/privkey.pem

auth:
  type: password
  password: TheIsPassword

masquerade:
  type: file
  file:
    dir: /site/public/
  listenHTTP: :80 
  listenHTTPS: :443 
  forceHTTPS: true 
```
