### DISCUSSION TITLE
我就是怎么弄都没法实现netflix走socks5，头疼死了，救救我

### DISCUSSION THREAD

**Discussion by imtv** [apernet/hysteria#899] [Q&A]
我把服务器的json放这，麻烦帮我看看吧
1.证书是自己acme申请的，可用
2.socks5也是好用的

```
listen: :443

tls:
  cert: /etc/ssl/hy2/cert.crt
  key: /etc/ssl/hy2/privkey.key

auth:
  type: password
  password: **********

acl:
  inline:
    - reject(all, udp/443)
    - reject(geoip:cn)
    - nf(geosite:netflix)
    - nf(geosite:disney)
    - direct(all)

outbounds:
  - name: direct
    type: direct
  - name: nf
    type: socks5
    socks5:
      addr: **.**.**.**:*****
      username: **********
      password: **********

masquerade:
  type: proxy
  proxy:
    url: https://bing.com/
    rewriteHost: true
```
