### DISCUSSION TITLE
userpass not work

### DISCUSSION THREAD

**Discussion by nicolauhk** [apernet/hysteria#940] [Q&A] [answered]
Dear All,
I try to use userpass but not success
here is my config in server side:
type: userpass
    user1: pass1
    user2: pass2
    user3: pass3

my client side
     user1:pass1

but not work

Is anyone can help me? Thanks

**Comment by haruue** [comment]
```yaml
auth:
  type: userpass 
  userpass: # <- don't miss this
    user1: pass1
    user2: pass2
    user3: pass3
```
