### DISCUSSION TITLE
请教，ACL规则无法正确使用

### DISCUSSION THREAD

**Discussion by zazitufu** [apernet/hysteria#947] [Q&A] [answered]
服务端使用的是v2.2.4
客户端使用的是v2rayN_v6.33,使用的也是v2.2.4

现象：

1、配置了一个服务端localhost的socks5下级代理（确认是能用的）
2、服务端使用config.yaml，在ACL规则使用具体的网站分流的情况下，不能实现指定网站走socks5出口
3、在ACL规则使用proxy(all)的情况下，能实现所有网站走socks5出口

请教是为什么会发生这样的现象？以及具体如何排查。
下面附上服务端的配置文件，这个配置使用proxy(all)是能正常运行的，如果把它注释掉，使用上面几行具体的规则，那几个网址就不能实现走socks5。
```
listen: :12345

tls:
  cert: /root/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/123.com/123.com.crt
  key: /root/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/123.com/123.com.key

quic:
  initStreamReceiveWindow: 16777216
  maxStreamReceiveWindow: 16777216
  initConnReceiveWindow: 33554432
  maxConnReceiveWindow: 33554432

auth:
  type: password
  password: password111

masquerade:
  type: proxy
  proxy:
    url: https://maimai.sega.jp
    rewriteHost: true


outbounds:
  - name: out_1
    type: direct
  - name: proxy1
    type: socks5
    socks5:
      addr: 127.0.0.1:50414
      username: user1
      password: password123

acl:
  inline:
#    - proxy1(geosite:openai)
#    - proxy1(geosite:google)
#    - proxy1(suffix:openai.com)
#    - proxy1(ip.me)
#    - reject(geoip:cn)
     - proxy1(all)
  geoip: /etc/hysteria/geoip.dat
  geosite: /etc/hysteria/geosite.dat
```

**Comment by ghost** [comment]
我复制你的outbonds和acl，下载最新的geoip.dat和geosite.dat，用frp搭建socks5代理，测试ip.me和ipinfo.io两个网站，你的规则是生效的。

![image](https://github.com/apernet/hysteria/assets/28730221/568cfe4f-a27d-4321-a715-78e3b033d906)
![image](https://github.com/apernet/hysteria/assets/28730221/57cb3818-feda-418f-b81f-76d00e354b8f)

**Comment by zazitufu** [comment]
> 我复制你的outbonds和acl，下载最新的geoip.dat和geosite.dat，用frp搭建socks5代理，测试ip.me和ipinfo.io两个网站，你的规则是生效的。
> 
> ![image](https://private-user-images.githubusercontent.com/28730221/306870156-568cfe4f-a27d-4321-a715-78e3b033d906.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1ODExNjAsIm5iZiI6MTcwODU4MDg2MCwicGF0aCI6Ii8yODczMDIyMS8zMDY4NzAxNTYtNTY4Y2ZlNGYtYTI3ZC00MzIxLWE3MTUtNzhlM2IwMzNkOTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDA1NDc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4OWIxYWI2MThkNjBjY2RjYWVlN2NmOWU5MmNiMDI1YWQ1M2VkNDllZTVkZTA2OGJlZTY2NzMxYTliMDUzNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UTpOFeSAHBfFNm5bxmKLTuzQeU3HJECq9g19qISRH8U) ![image](https://private-user-images.githubusercontent.com/28730221/306870223-57cb3818-feda-418f-b81f-76d00e354b8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1ODExNjAsIm5iZiI6MTcwODU4MDg2MCwicGF0aCI6Ii8yODczMDIyMS8zMDY4NzAyMjMtNTdjYjM4MTgtZmVkYS00MThmLWI4MWYtNzZkMDBlMzU0YjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDA1NDc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5YmZjNjgyZDJjNzhjM2M2M2YzNTYwZDRjY2MwM2QwYTVlZGFlYzAyNTRjOWEzY2I2YmU3YmI0ZTZjYzgzNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I82gcUVFou94moEiH7VTg2DLDwnsSkeaRbzTL22yLx8)

====
哈哈，第一次遇到也是zazi

请问把 proxy1(all)注释掉，用下面这个规则是否能生效？我试得头很大，不知道是什么地方出错了。还有就是请教一下您的客户端使用的是什么？也是v2rayN吗？
```
acl:
  inline:
    - proxy1(geosite:openai)
    - proxy1(geosite:google)
    - proxy1(suffix:openai.com)
    - proxy1(ip.me)
    - reject(geoip:cn)
```

**Reply by ghost** [reply]
是v2rayN，生效的
![image](https://github.com/apernet/hysteria/assets/28730221/f674e2de-52fa-46c8-9956-9d86006d235c)

**Reply by zazitufu** [reply]
真是苦恼啊，看上去服务端的配置文件写法是正确的。

但是我这里真的无法通过acl对域名进行outbound选择。访问ip.me的时候，还是服务端的ip，不是那个socks5 outbound的ip。

现在唯一能想到的就是我本机上用的v2rayN，发送访问目标过去给服务端的时候，是解析过的ip而不是域名，所以在服务端的acl规则里面不能根据域名来进行outbound选择，但是使用 proxy(all)却能生效。

我在官方文档里面找不到如何实时查看hy2服务端接收到的是ip还是域名，搜索issue和google也搜不到。如果您知道请赐教，谢谢

我刚才试了在本地ping，以及在服务端ping那个 ip.me的域名，获得同样的都是`212.102.35.236`这个ip，然后我在服务端的acl里面，把这个ip地址也加进去，重启hy2之后，访问 ip.me 能显示socks5 outbound的ip了。

不知道您有无什么解决思路可以介绍一下？如果您得空方便的话，能否请告知一下您的V2rayN的版本，还有里面参数、路由、DNS的设置之类的截图？感谢！
```
acl:
  inline:
    - proxy1(geosite:openai)
    - proxy1(geosite:google)
    - proxy1(suffix:ip.me)
    - proxy1(ip.me)
    - proxy1(212.102.35.236)
    - reject(geoip:cn)
#    - proxy1(all)
  geoip: /etc/hysteria/geoip.dat
  geosite: /etc/hysteria/geosite.dat

```
