### ISSUE TITLE
测速问题

### ISSUE THREAD

**Issue by stqfdyr** [apernet/hysteria#1002]
### 1、描述：

我配置文件开启了允许测速，想进行测速，结果测不了

### 2、服务端配置：
```yaml
# 略
auth:
  type: userpass
  userpass:
    xxxx: xxxxxxxxxxxxxxx
speedTest: true
# 略
```
虽然略了很多，但确定配置无误，可以正常启动 hy2

然后我就在命令行输入了 `hysteria speedtest` 想进行测速（不知道是不是因为不是这样测的啊？），结果出现以下报错：
```
2024-03-24T01:36:50+08:00       INFO    speed test mode
2024-03-24T01:36:50+08:00       FATAL   failed to parse client config   {"error": "1 error(s) decoding:\n\n* 'auth' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[type:userpass userpass:map[xxxx:xxxxxxxxxxxxxxx]]'"}
```
突然就无法解析 `userpass` 这样的配置了

我还试了 `/path/hysteria/binaryfile speedtest` 也是同样的结果
