### ISSUE TITLE
如何使用 ip 进行连接

### ISSUE THREAD

**Issue by suchangv** [apernet/hysteria#1007]
记得之前搭建的 hysteria 2 在客户端是可以使用 ip 进行连接的，后面某次更新后，就只能使用域名进行连接了

我使用的是 CA 证书进行搭建的

**Comment by haruue** [comment]
```
server: IP地址:443

tls:
  sni: 证书上的域名
  ca: 根证书文件
  #insecure: true # 或者关闭证书验证
```

如果你的证书是由可信 CA 签署的， 不需要指定 `ca`。
如果你的证书是签发给 IP 地址的， 不需要指定 `sni`。

建议提供你在服务端和客户端上使用的配置文件， 客户端连接不上时的报错输出， 以获取更多帮助。
