### ISSUE TITLE
最近时常断联

### ISSUE THREAD

**Issue by toyo2333** [apernet/hysteria#1017]
```
2024-03-31T04:25:00Z    INFO    client connected        {"addr": "ip:port", "id": "user", "tx": 6250000}
2024-03-31T04:25:29Z    INFO    client disconnected     {"addr": "ip:port", "id": "user", "error": "accepting stream failed: timeout: no recent network activity"}
```
无法使用
Server配置简单，之前一直正常

```
listen: :443

acme:
    domains:
        - www.mydomain.com 
    email: xxx@somme.com

auth:
    type: password
    password: xxxxxxxx
  
masquerade:
    type: proxy
    proxy:
        url: https://some-oversea.com
        rewriteHost: true
```
docker部署的，v2.3.0也是这样。

请问怎么解决呢？
