### ISSUE TITLE
如何设置vps中不同网站出口对应不同的网卡

### ISSUE THREAD

**Issue by cloveric** [apernet/hysteria#1031]
套warp后，确实可以通过socks5的形式，比如正常网站通过直连走，netflix通过socks5方式走，例如这样：

outbounds:
- name: v4
type: direct
direct:
mode: 4
- name: warp
type: socks5
socks5:
addr: 127.0.0.1:4000
acl:
geosite: geosite.dat
inline:
- warp(geosite:netflix)

但是这种方式看netflix，需要对dns进行些设置，比如手机端使用的时候，用nekobox的话就要把fakedns打开。如果通过路由（梅林）前置翻墙的话，电视端上面还是只能看netflix自制剧。

如果warp全局的话，上面socks5的小问题就存在，但是会影响整体速度。

然后warp是由非全局模式的，warp相当于一块网卡，我的思路是普通网站通过vps的自己网卡去访问，netfilx通过warp的网卡访问，但是看了一圈官方文档，以及issue都没有提到。所以想求助一下这块yaml怎么写，我在之前的issue看到hysteria已经支持多网卡。

**Comment by haruue** [comment]
用这里的 bindDevice 可以吗？
https://hysteria.network/docs/advanced/Full-Server-Config/#customizing-direct-outbound

假设你的 warp 网卡叫做 `cfwarpwg0`

```yaml
outbounds:
  - name: v4
    type: direct
    direct:
      mode: 4
  - name: warp
    type: direct
    direct:
      mode: auto
      bindDevice: cfwarpwg0

acl:
  geosite: geosite.dat
  inline:
    - warp(geosite:netflix)
```
