### ISSUE TITLE
socks5无法指定ipv6出口？

### ISSUE THREAD

**Issue by ckaak** [apernet/hysteria#1036]
**描述问题**
我用warp建立一个本地40000端口socks5代理，然后我发现它只能使用warp的IPV4出口，然后我在socks5子级加了一个mode: 6，发现并没有用。出口还是warp ipv4

**如何复现**
```
outbounds:
  - name: hoho
    type: direct
    direct:
      mode: 46
  - name: socks5
    type: socks5
    socks5:
      addr: 127.0.0.1:40000
      mode: 6
```

**预期行为**
socks5可以指定ipv4/ipv6出口

**日志**
附上客户端/服务器端在错误发生前后的日志。

**设备和操作系统**
debian11

**额外信息**
其他你认为有助于解决问题的信息。
