### ISSUE TITLE
双栈机器使用direct出站时无法使用系统默认v4/v6出站

### ISSUE THREAD

**Issue by maoxikun** [apernet/hysteria#1039]
**描述问题**
使用官方脚本安装hy2，系统默认使用ipv6出站，但是hy2使用direct出站时是随机的。

**如何复现**
hy2服务端配置如下：
```yaml
listen: :443
tls:
  cert: /etc/hysteria/xxxx.crt
  key: /etc/hysteria/xxxx.key
bandwidth:
  up: 1 gbps
  down: 1 gbps
auth:
  type: password
  password: xxxxxxxx
acl:
  inline:
    - reject(all, udp/443)
    - direct(all)
```

**预期行为**
hy2使用direct出站时使用ipv4/ipv6应该和系统一致。

**日志**
```log
hysteria[843]: 2024-04-14T20:53:39-07:00        INFO        server mode
hysteria[843]: 2024-04-14T20:53:39-07:00        INFO        server up and running        {"listen": ":64241"}
hysteria[843]: 2024-04-14T20:54:13-07:00        INFO        client connected        {"addr": "117.61.109.220:63028", "id": "user", "tx": 6250000}
```

**设备和操作系统**
服务端：`Linux zz 6.1.0-20-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.85-1 (2024-04-11) x86_64 GNU/Linux`
客户端：`Darwin zz.local 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:31 PST 2024; root:xnu-10063.101.15~2/RELEASE_X86_64 x86_64`

**额外信息**
<img width="564" alt="image" src="https://github.com/apernet/hysteria/assets/106460972/e88001a3-e2fb-47bf-b22c-c34684bad6c4">

**Comment by maoxikun** [comment]
将服务端改为如下配置时能正常使用ipv4/ipv6出站（而不是随机的）：
```yaml
listen: :443
tls:
  cert: /etc/hysteria/xxxx.crt
  key: /etc/hysteria/xxxx.key
bandwidth:
  up: 1 gbps
  down: 1 gbps
auth:
  type: password
  password: xxxxxxxx
acl:
  inline:
    - reject(all, udp/443)
#  - direct4(all)
    - direct6(all)
outbounds:
  - name: direct4
    type: direct
    direct:
      mode: 46
  - name: direct6
    type: direct
    direct:
      mode: 64
```
