### ISSUE TITLE
服务器hy1和hy2如何同时warp代理

### ISSUE THREAD

**Issue by ypxun** [apernet/hysteria#1048]
我这种情况的hy2流量该如何转发呢？<br>
我这边运营商QoS比较厉害，hy2即使用端口跳跃也不太好用，反而是hy1的wechat-video协议能不被QoS。我就用[Hi_Hysteria](https://github.com/emptysuns/Hi_Hysteria)这个脚本搭了hy1（v1.3.5）的代理，参考#594 服务器将所有hy1流量通过xray转发到warp。<br>
服务器配置文件加了：
```
"socks5_outbound": {
    "server": "55.66.77.88:1080", // SOCKS5 服务器地址
  }
```
然后我发现我在客户端遗留的hy2配置，依然能够正常使用，但hy2的流量无法走warp。请问有方法再添加hy2的端口做socks5转发吗？

**Comment by haruue** [comment]
用 outbound 和 acl 实现

```yaml
outbounds:
  - name: cfwarp
    type: socks5
    socks5:
      addr: "55.66.77.88:1080"

acl:
  inline:
    - cfwarp(all)
```

请参阅下列文档， 是中文的：
+ https://hysteria.network/zh/docs/advanced/Full-Server-Config/#outbounds
+ https://hysteria.network/zh/docs/advanced/Full-Server-Config/#acl
+ https://hysteria.network/zh/docs/advanced/ACL/
