### ISSUE TITLE
用官方代码搭建成功需要改dns为国外dns才能正常上国外网站，用sing-box搭建不需要

### ISSUE THREAD

**Issue by luii2020** [apernet/hysteria#1069]
**描述问题**
用官方代码搭建成功
服务端配置文件如下
```yaml
listen: :8443 

tls:
  cert: /home/aa.crt 
  key: /home/aa.key 

auth:
  type: password
  password: fdafdagfegers 

masquerade: 
  type: proxy
  proxy:
    url: https://www.bing.com/ 
    rewriteHost: true
```
服务器启动成功，用passwall设置成功，测试都是通的，就是不能上国外网站，最后把电脑或手机的dns设置从223.5.5.5改为8.8.8.8就正常了，我另外一个节点用sing-box的一键脚本搭建，只要测试是通的，dns改不改都能正常使用

**预期行为**
你认为修复后的行为应该是怎样的。

**日志**
日志没有错误

**设备和操作系统**
服务器Ubuntu20.04，客户端是openwrt R24.4.4 的passwall 4.77-5，Hysteria 版本
【 v2.4.3 】，
