### ISSUE TITLE
启动问题

### ISSUE THREAD

**Issue by lbbboy** [apernet/hysteria#1079]
**描述问题**
已经启动端口tcping 不通，机器以前装有xray。xray启动后。tcping端口正常。防火墙规则正常。

**如何复现**
安装
```
bash <(curl -fsSL https://get.hy2.sh/)

修改配置
/etc/hysteria/config.yaml
# listen: :443

acme:
  domains:
    - my.domains
  email: my@email.com

auth:
  type: password
  password: ******

masquerade:
  type: proxy
  proxy:
    url: https://bing.com
    rewriteHost: true

启动
systemctl start hysteria-server.service
```
**预期行为**
acme 证书申请成功 hysteria运行正常

**日志**
```
systemd[1]: Started Hysteria Server Service (config.yaml).
hysteria[107424]: 2024-05-11T03:33:15+08:00        INFO        server mode
hysteria[107424]: 2024-05-11T03:33:15+08:00        INFO        maintenance        started background certificate maintenance        {"cache": "0x40001851f0"}
 server up and running        {"listen": ":443"}
```
```
udp6       0      0 :::443                  :::*                                107424/hysteria
```
**设备和操作系统**
debian11 

**额外信息**
甲骨文 ARM VPS
