### ISSUE TITLE
有关服务端伪装使用静态文件方式的问题

### ISSUE THREAD

**Issue by dyqnaruto** [apernet/hysteria#1091]
**你的功能请求是否与某个问题有关？**
(https://hysteria.network/zh/docs/advanced/Full-Server-Config/#masquerade)
我使用了一个静态html文件用作伪装，把他放在/root/web文件夹中，路径为/root/web/index.html
服务端相关配置为：
```
masquerade:
  type: file
  file:
    dir: /root/web/index.html
```
发现无法访问网页，请问我该如何解决，由于我个人不太懂web相关配置，可以告诉我一个示例配置吗？
谢谢！
**描述你希望的解决方案**
请尽量清晰精准地描述你希望的解决方案。

**有没有其他替代方案**
请尽量清晰精准地描述你认为可能的替代方案。

**额外信息**
其他你认为有助于开发者了解你需求的信息。
