### ISSUE TITLE
DNS (Resolver) tag in server side config has no effect

### ISSUE THREAD

**Issue by robin98** [apernet/hysteria#1111]
**Describe the bug**
I tried the `resolver` tag on my server side config at `/etc/hysteria/config.yaml` like this;
but this method didn't work for my clients as their resolver didn't change from alibaba to any other DNS resolver I specified.

```
listen: :8443

tls:
  cert: /opt/cert/xxxx/fullchain.pem
  key: /opt/cert/xxxx/privkey.pem

auth:
  type: password
  password: xxxx

masquerade:
  type: proxy
  proxy:
    url: https://xxxx.com/
    rewriteHost: true

resolver:
  type: udp
  udp:
    addr: 9.9.9.9:53
    timeout: 10s
```

**Logs**

![dns](https://github.com/apernet/hysteria/assets/22413785/d677d62b-4758-4961-b325-8503a98423fe)

**Device and Operating System**
ubuntu server 22.04.4
