### ISSUE TITLE
Docker部署后，仅接受部分ip的连接

### ISSUE THREAD

**Issue by JoJenH** [apernet/hysteria#1123]
**描述问题**
使用Docker部署Hysteria2，映射端口到外部，发现无法访问。
下图为Hysteria2与对照组headscale端口映射详情，不存在仅映射本地情况：
![image](https://github.com/apernet/hysteria/assets/45531537/b3812881-3839-497a-a163-4fb4094c7391)

客户端通过外网连接，提示timeout：
![image](https://github.com/apernet/hysteria/assets/45531537/4819b8e9-5837-4032-aaef-799e2e3a5242)

根据文档排查，未发现相关异常：
![image](https://github.com/apernet/hysteria/assets/45531537/764ecaf7-d674-48fa-bc25-709fb3b53c55)
服务正常运行：
![image](https://github.com/apernet/hysteria/assets/45531537/a22c8c22-838d-4803-9a7f-3600d7dc45b2)
防火墙等问题下图由内网实验不作考虑；未设置混淆，根据文档删除相关字段；服务器内核版本为5.x。

**如何复现**
```yaml
  hysteria:
    image: tobyxdd/hysteria
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
    ports:
      - '10443:443'
    volumes:
      - ${DATA_PATH}/network/hysteria/hysteria.yaml:/etc/hysteria/hysteria.yaml
      - ${CA_PATH}/hysteria/hysteria.crt:/etc/hysteria/hysteria.crt
      - ${CA_PATH}/hysteria/hysteria.key:/etc/hysteria/hysteria.key
    command: ["server", "-c", "/etc/hysteria/hysteria.yaml"]
```
docker-compose文件如上，未设置host模式，转发端口，不确定是否有影响。
```yaml
# listen: :443

tls:
  cert: /etc/hysteria/hysteria.crt
  key: /etc/hysteria/hysteria.key

auth:
  type: password
  password: ********
```
Hysteria2配置如上，未设置混淆。
![image](https://github.com/apernet/hysteria/assets/45531537/e6ddf5a9-f78e-4505-a3fb-1774591ba200)
nc试图连接端口，发现仅通过127.0.0.1可连接，通过主机网卡ip10.168.0.10发现无法连接，导致公网无法访问。
**预期行为**
通过10.168.0.10:10443应正常访问，进而公网可正常使用。

**日志**
无其它日志生成

**设备和操作系统**
PVE

**额外信息**
使用host网络后发现仅监听UDP端口，不清楚是否为正常现象：
![image](https://github.com/apernet/hysteria/assets/45531537/c94f4369-4e61-43d1-a2d7-d2017296e981)

**Comment by JoJenH** [comment]
补充：host模式测试正常，问题解决，将进一步测试仅转发UDP端口

**Comment by JoJenH** [comment]
仅转发UDP正常，抱歉叨扰。
提供compose文件供不希望使用host模式部署场景作为参考：
```yaml
hysteria:
    image: tobyxdd/hysteria
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
    ports:
      - '10443:10443/udp'
    volumes:
      - ${DATA_PATH}/network/hysteria/hysteria.yaml:/etc/hysteria/hysteria.yaml
      - ${CA_PATH}/hysteria/hysteria.crt:/etc/hysteria/hysteria.crt
      - ${CA_PATH}/hysteria/hysteria.key:/etc/hysteria/hysteria.key
    command: ["server", "-c", "/etc/hysteria/hysteria.yaml"]
```
