### ISSUE TITLE
使用DNS服务解锁奈飞的疑惑

### ISSUE THREAD

**Issue by FFFKLD** [apernet/hysteria#1132]
纯小白，摸索了很久，希望大佬们解惑：我购买了某网站的DNS解锁服务，这是我的服务端和客户端配置，实际测试可以解锁奈飞和访问外网，但请问大佬们这样配置是否会降低访问其他网站的网速，是否需要额外增加outbands和acl指向奈飞？
```
listen: :5499 #监听端口

#使用自签证书
tls:
  cert: /etc/hysteria/server.crt
  key: /etc/hysteria/server.key

auth:
  type: password
  password: 123456 #设置认证密码

resolver:
  type: udp
  udp:
    addr: x.x.x.x:53（解锁奈飞的DNS）
    timeout: 4s

masquerade:
  type: proxy
  proxy:
    url: https://bing.com #伪装网址
    rewriteHost: true
```
以下为客户端配置
```
server: x.x.x.x:5499(vps地址)
auth: 123456

bandwidth:
  up: 100 mbps
  down: 100 mbps

tls:
  sni: bing.com
  insecure: true #使用自签时需要改成true

socks5:
  listen: 127.0.0.1:1080
http:
  listen: 127.0.0.1:8080
```
