### ISSUE TITLE
Wireguard Outbound

### ISSUE THREAD

**Issue by bart3nder** [apernet/hysteria#1143]
Hello! thanks for the great project. Is it possible to implement Wireguard outbound or custom network interface (like traffic goes to `eth9` instead of `eth0`) in direct outbound in Hysteria2?  It would be helpful in circumstances where server's IP is flagged as spam and etc. 
Thanks!
Edit 1: My bad, found the custom interface in docs, just the Wireguard outbound is suggested now :D

**Comment by haruue** [comment]
You can use `bindDevice` in a `direct` outbound.

https://hysteria.network/docs/advanced/Full-Server-Config/#customizing-direct-outbound

For example, if your WireGuard interface is named `wg0`, you can configure the outbound as follows

```yaml
outbounds:
  - name: cfwarp
    type: direct
    direct:
      mode: auto
      bindDevice: wg0
```
