### ISSUE TITLE
使用docker-compose启动客户端,curl报错:curl: (97) Recv failure: 连接被对方重置

### ISSUE THREAD

**Issue by earth-hotfix** [apernet/hysteria#1172]
**描述问题**
请尽量清晰精准地描述你遇到的问题。

使用docker-compose启动客户端,
执行 curl --socks5 127.0.0.1:12803 ip.sb 报错:curl: (97) Recv failure: 连接被对方重置
如果使用第三客户端,如ios小火箭等可以正常使用
**如何复现**
复现问题的步骤。
我的服务端配置
```
# listen: :443 
acme:
  domains:
    - 111.com
  email: admin@111.com 

auth:
  type: password
  password: 11111

masquerade: 
  type: proxy
  proxy:
    url: https://www.xxx.com
    rewriteHost: true
```
我的客户端配置
```
server: 111.com:443

auth: 11111

tls:
  insecure: true #使用自签时需要改成true

fastOpen: true
lazy: true

socks5:
  listen: 127.0.0.1:12801
http:
  listen: 127.0.0.1:8080
```

我的docker-compose配置
```
  hy2:
    image: images:alpine
    container_name: hy2-client
    ports:
      - 12803:12801
    restart: always
```

**预期行为**
你认为修复后的行为应该是怎样的。

curl使用socks5代理正常

**日志**
docker-compose启动后输出的日志
hy2-client  | 2024-07-31T19:46:16+08:00 INFO    client mode
hy2-client  | 2024-07-31T19:46:16+08:00 INFO    use this URI to share your server       {"uri": "hysteria2://11111@111.com:443/?insecure=1"}
hy2-client  | 2024-07-31T19:46:16+08:00 INFO    HTTP proxy server listening     {"addr": "127.0.0.1:8080"}
hy2-client  | 2024-07-31T19:46:16+08:00 INFO    SOCKS5 server listening {"addr": "127.0.0.1:12801"}

**设备和操作系统**
客户端运行在linux上。

**额外信息**
其他你认为有助于解决问题的信息。
