### ISSUE TITLE
求确认关于ACL的问题，无法大陆直连/域名直连

### ISSUE THREAD

**Issue by zyppe** [apernet/hysteria#1193]
````
server: hysteria2://
socks5:
  listen: 127.0.0.1:2080
acl:
  inline:
    - reject(geoip:cn)
    - reject(geosite:cn)
    - reject(suffix:ipinfo.io)
  geoip: geoip.dat
  geosite: geosite.dat
  geoUpdateInterval: 168h
````
如上配置没有二次套娃，直接在cli里面运行（直接使用socks5提供的端口）
geoip.dat geosite.dat 都自动被下载下来了，无论我写成`reject`还是`direct`都无法强制绕过大陆地址，ipinfo.io解析出来的也是服务器地址。
我不需要复杂的outbounds，只需要在ACL里面直接绕过。
