### ISSUE TITLE
Client not being connected to sever even if server shoes the logs of up and running

### ISSUE THREAD

**Issue by shivani446** [apernet/hysteria#1207]
I have deployed hysteria2 server and it shows the logs of server up and running 
![image](https://github.com/user-attachments/assets/049afd8d-5158-4599-bdb5-7969b9ab6a8b)
but when I try to connect to the sever client shows this error 
![Screenshot from 2024-09-23 12-15-21](https://github.com/user-attachments/assets/bc305219-28b3-46ea-ae78-7b09bb693010)
This is my values for server , I tried with both acme and tls which works fine 
```
    listen: :443 

    tls:
      cert: tls.crt
      key: tls.key
    # acme:
    #   domains:
    #     - domain

    auth:
      type: password
      password: "my_pass"

    masquerade: 
      type: proxy
      proxy:
        url: "https://news.ycombinator.com/" 
        rewriteHost: true
```

and client values follows
```
server: domain:443

auth: "pass"

bandwidth: 
  up: 20 mbps
  down: 100 mbps

lazy: true

tls:
  insecure: true

socks5:
  listen: 127.0.0.1:1080

http:
  listen: 127.0.0.1:8088
  ```
  I am aware of this docs
  https://v2.hysteria.network/docs/advanced/Troubleshooting/
  the sever running on ubuntu >>22.04
  
  i would like to debug it further If might be helpful if i can debug that the server is properly running or not, I have added the debug logs but when i try to connect the client the server does not show any logs as the request from client itself is not reaching to sever.
