### ISSUE TITLE
tproxy + port forward?

### ISSUE THREAD

**Issue by iopq** [apernet/hysteria#1209]
I got everything to work, except when I simply add port forwarding like so:

```
tcpForwarding:
  - listen: 127.0.0.1:6112
    remote: MY_SERVER_ADDRESS:6112

udpForwarding:
  - listen: 127.0.0.1:6112
    remote: MY_SERVER_ADDRESS:6112
    timeout: 20s
```

it doesn't appear to be forwarded

what am I doing wrong?
