### ISSUE TITLE
伪装代理失败

### ISSUE THREAD

**Issue by DamonLee35** [apernet/hysteria#1227]
**描述问题**
开启伪装代理网址，无法正确转到代理地址

**如何复现**
开启代理伪装，访问域名或服务器IP

**预期行为**
转到代理网址

**额外信息**
返回502错误代码

**Comment by haruue** [comment]
您好。 请提供 Hysteria 服务端配置文件内容， 我们才能帮您解决问题。

**Comment by DamonLee35** [comment]
如图
![Uploading IMG_20241019_130153.jpg…]()

**Comment by DamonLee35** [comment]
如图
![IMG_20241019_130153](https://github.com/user-attachments/assets/41d5735e-2973-4e80-b1ef-e40b6d975bb7)

**Comment by DamonLee35** [comment]
补充，我使用的监听端口不是默认的443端口，证书使用的是自签名证书，不知道是不是和这些有关？

**Comment by haruue** [comment]
您好。

请这样配置伪装

```
masquerade:
  type: proxy
  proxy:
    url: https://www.wps.com
    rewriteHost: true
  listenHTTP: :80
  listenHTTPS: :443
  forceHTTPS: true
```
