### ISSUE TITLE
有最基础的配置吗？

### ISSUE THREAD

**Issue by yorks** [apernet/hysteria#1234]
**描述问题**
看了一遍文档，自己写了配置，发现没办法搞通。
帮忙看看哪里不对？

**如何复现**
server config.yaml:
```yaml
listen: :443
tls:
  cert: /etc/hysteria/1778888.xyz.cer
  key: /etc/hysteria/1778888.xyz.key

auth:
  type: password
  password: PioInzaItPddN6rKhnwCreDx

obfs:
  type: salamander
  salamander:
    password: cyr_Me_A_r1ver

masquerade:
  type: proxy
  proxy:
    url: https://cn.bing.com/
    rewriteHost: true
```

client client.yaml:
```yaml
server: 127.0.0.1:443
tls:
  sni: h3.1778888.xyz
auth: PioInzaItPddN6rKhnwCreDx
iobfs:
  type: salamander
  salamander:
    password: cyr_Me_A_r1ver
lazy: true
socks5:
  listen: "127.0.0.1:1080"
tcpForwarding:
  - listen: "127.0.0.1:1443"
    remote: "127.0.0.1:443"
```
**启动方式 server**
```bash
systemctl status hysteria-server.service --no-pager -l 
● hysteria-server.service - Hysteria Server Service (config.yaml)
     Loaded: loaded (/etc/systemd/system/hysteria-server.service; disabled; preset: disabled)
     Active: active (running) since Tue 2024-10-29 06:42:12 UTC; 14min ago
   Main PID: 1605980 (hysteria)
      Tasks: 4 (limit: 1114)
     Memory: 5.2M
        CPU: 55ms
     CGroup: /system.slice/hysteria-server.service
             └─1605980 /usr/local/bin/hysteria server --config /etc/hysteria/config.yaml

Oct 29 06:42:12 ip-172-31-42-153.ap-northeast-1.compute.internal systemd[1]: Started hysteria-server.service - Hysteria Server Service (config.yaml).
Oct 29 06:42:12 ip-172-31-42-153.ap-northeast-1.compute.internal hysteria[1605980]: 2024-10-29T06:42:12Z        INFO        server mode
Oct 29 06:42:12 ip-172-31-42-153.ap-northeast-1.compute.internal hysteria[1605980]: 2024-10-29T06:42:12Z        INFO        server up and running        {"listen": ":443"}
```
**启动client:**
```bash
[root@ip-172-31-42-153 hysteria]# /usr/local/bin/hysteria client -c client.yaml -l debug &
[2] 1607470
[root@ip-172-31-42-153 hysteria]# 2024-10-29T06:59:18Z	INFO	client mode
2024-10-29T06:59:18Z	INFO	use this URI to share your server	{"uri": "hysteria2://PioInzaItPddN6rKhnwCreDx@127.0.0.1:443/?sni=h3.1778888.xyz"}
2024-10-29T06:59:18Z	INFO	TCP forwarding listening	{"addr": "127.0.0.1:1443", "remote": "127.0.0.1:443"}
2024-10-29T06:59:18Z	INFO	SOCKS5 server listening	{"addr": "127.0.0.1:1080"}

[root@ip-172-31-42-153 hysteria]# ss -ntlp | grep :1080
LISTEN 0      4096       127.0.0.1:1080       0.0.0.0:*    users:(("hysteria",pid=1607470,fd=6))                       
[root@ip-172-31-42-153 hysteria]# ss -nulp | grep :443
UNCONN 0      0                                    *:443             *:*    users:(("hysteria",pid=1605980,fd=3))     
[root@ip-172-31-42-153 hysteria]# ss -ntlp | grep :1443
LISTEN 0      4096       127.0.0.1:1443       0.0.0.0:*    users:(("hysteria",pid=1607470,fd=3))                       
[root@ip-172-31-42-153 hysteria]# export ALL_PROXY=socks://127.0.0.1:1080
[root@ip-172-31-42-153 hysteria]# curl https://www.baidu.com 
curl: (97) Recv failure: Connection reset by peer
[root@ip-172-31-42-153 hysteria]# unset ALL_PROXY
[root@ip-172-31-42-153 hysteria]# curl https://127.0.0.1:1443 -v
*   Trying 127.0.0.1:1443...
2024-10-29T07:00:23Z	DEBUG	TCP forwarding connect	{"addr": "127.0.0.1:44834"}
* Connected to 127.0.0.1 (127.0.0.1) port 1443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
*  CApath: none
2024-10-29T07:00:28Z	WARN	TCP forwarding error	{"addr": "127.0.0.1:44834", "error": "connect error: timeout: no recent network activity"}
* Recv failure: Connection reset by peer
* OpenSSL SSL_connect: Connection reset by peer in connection to 127.0.0.1:1443 
* Closing connection
curl: (35) Recv failure: Connection reset by peer
[root@ip-172-31-42-153 hysteria]# curl https://127.0.0.1:443  -k
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**设备和操作系统**
aws 云主机
[root@ip-172-31-42-153 hysteria]# uname -r
6.1.56-82.125.amzn2023.x86_64

server/client 都是本机操作。
iptables 本地 127.0.0.1 网络是放通的。
[root@ip-172-31-42-153 hysteria]# iptables -S | grep 127.0.
-A INPUT -s 127.0.0.0/8 -j ACCEPT

版本信息：
```yaml
Version:	v2.5.2
BuildDate:	2024-10-06T04:48:44Z
BuildType:	release
CommitHash:	b960beabbd4bbdedc49c7b4f08ad137a4ee70442
Platform:	linux
Architecture:	amd64
```

**额外信息**
帮忙看看配置是是不是少了啥？有没一个最基础的配置参考？？

**Comment by haruue** [comment]
您好， 您上面提供的客户端配置文件中

``` yaml
iobfs:  # <- 这里多了个 i
  type: salamander
  salamander:
    password: cyr_Me_A_r1ver
```
