### ISSUE TITLE
open ./.hysteria-geoloader.dlpart.xxxxxx: permission denied

### ISSUE THREAD

**Issue by NP-Prob** [apernet/hysteria#1260]
**描述问题**
启动hysteria2发生错误：
`{"error": "open ./.hysteria-geoloader.dlpart.1644212360: permission denied"}`

**如何复现**
安装流程如下：

1. 安装
`cd ~ && bash <(curl -fsSL https://get.hy2.sh/)`

2. 修改权限：
`chmod a+w /etc/hysteria`

3. 修改配置：`/etc/hysteria/config.yaml`
配置如下（已做脱敏处理）：
```
listen: :xxxx

tls:
  cert: /etc/hysteria/cert/fullchain.pem
  key: /etc/hysteria/cert/privkey.pem

auth:
  type: password
  password: xxxxxxxxx

resolver:
  type: https
  https:
    addr: 8.8.8.8:443
    timeout: 10s
    sni: dns.google
    insecure: false

acl:
  inline:
    - reject(geoip:cn)
    - ipv4(all)

outbounds:
  - name: ipv4
    type: direct
    direct:
      mode: 4

bandwidth:
  up: 100 mbps
  down: 100 mbps

speedTest: true

masquerade:
  type: proxy
  proxy:
    url: https://example.com/
    rewriteHost: true
```

4. 将`hysteria-server.service`中的运行组和用户改为root

5. 重启hysteria2

**预期行为**
正常运行hysteria2

**日志**
```
systemd[1]: Started hysteria-server.service - Hysteria Server Service (config.yaml).
hysteria[256060]: 2024-11-26T10:29:56-05:00        INFO        server mode
hysteria[256060]: 2024-11-26T10:29:56-05:00        INFO        downloading database        {"filename": "geoip.dat", "url": "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"}
hysteria[256060]: 2024-11-26T10:29:56-05:00        ERROR        failed to download database        {"error": "open ./.hysteria-geoloader.dlpart.1644212360: permission denied"}
hysteria[256060]: 2024-11-26T10:29:56-05:00        FATAL        failed to load server config        {"error": "invalid config: acl.inline: error at line 1: open ./.hysteria-geoloader.dlpart.1644212360: permission denied"}
systemd[1]: hysteria-server.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: hysteria-server.service: Failed with result 'exit-code'.
```

**设备和操作系统**
Debian GNU/Linux 12

**额外信息**
不确定是否是bug，网上查了一圈貌似没见到类似的情况，提交issue的时候只看到report bug选项合适。
