### ISSUE TITLE
请问手动指定tls证书后，如果证书文件更新了，需要重启hysteria server吗？

### ISSUE THREAD

**Issue by jearton** [apernet/hysteria#1270]
```yaml
tls:
  cert: /etc/nginx/ssl/xxx/fullchain.cer
  key: /etc/nginx/ssl/xxx/private.key
```

tls 证书由其它进程负责自动签发并定期更新，如果证书文件被更新了，hysteria server是否需要restart？
