### ISSUE TITLE
一些 ACL DNS 的问题

### ISSUE THREAD

**Issue by NEX-S** [apernet/hysteria#1277]
我想简单的在客户端进行分流，国外走 hy2 小鸡，国内走直连，查看了文档但是好像不支持在客户端做 ACL 分流

我的使用场景：wireguard 开启了 utun4 代理所有的流量（这个是用来穿透校园网的），hy2 使用 tun 模式通过 wireguard 的转发连接到小鸡，我想让 hy2 代理国外的流量，国内的就直接走 wireguard 的 utun4

遇到的问题：
在上面的情况下，tun 模式无法正常访问网站（服务端设置了 dns 解析地址），开启 cloudflare warp 的 dns 后才能正常访问网站
在 tun 模式下 dns 似乎走了本地解析，查了 issue 好像是要等更新？

希望hy2 支持的功能：
1. 在客户端支持 ACL
2. 不开启 cloudflare warp dns 的情况下，如何让 hy2 tun 正常工作

配置文件：
+ 客户端：
```
server: ...:20000-50000

transport:
  udp:
    hopInterval: 10s

auth: ...

tls:
  insecure: true
  pinSHA256: ...

bandwidth:
  up: 100 mbps
  down: 100 mbps

fastOpen: true

# socks5:
#   listen: 127.0.0.1:1080
# http:
#   listen: 127.0.0.1:1080

quic:
  maxIdleTimeout: 30s
  keepAlivePeriod: 2s
  disablePathMTUDiscovery: false

tun:
  name: "utun10" 
  mtu: 1500 
  timeout: 5m 
  address: 
    ipv4: 100.100.100.101/30
    ipv6: 2001::ffff:ffff:ffff:fff1/126
  route: 
    ipv4: [0.0.0.0/0] 
    ipv6: ["2000::/3"] 
    ipv4Exclude: [.../32]
    ipv6Exclude: ["2001:db8::1/128"]
```

服务端：
```
listen: :443

tls:
  cert: /etc/hysteria/test.crt
  key: /etc/hysteria/test.key

auth:
  type: password
  password: ...

masquerade:
  type: proxy
  proxy:
    url: https://httpbin.org/
    rewriteHost: true

resolver:
  udp:
    addr: 1.1.1.1:53
    timeout: 10s

bandwidth:
  up: 100 mbps
  down: 100 mbps
```
