### ISSUE TITLE
masquerade的proxy模式能否可以实现类似nginx sub_filter功能，来替换proxy网页内的内容

### ISSUE THREAD

**Issue by XxyokixX** [apernet/hysteria#1295]
**你的功能请求是否与某个问题有关？**
```
masquerade: proxy
proxy:
    url: https://some.site.net 
    rewriteHost: true
```
当使用hysteria2的proxy伪装模式时，hysteria2仅会“简单”的反代一下目标网站，不会替换网页内的域名地址
例如: 当目标地址是https://google.com 时，proxy成功后，点击一下google icon还是会跳转到google.com，而不是我的伪装地址
**这导致这个伪装看起来不那么真**

所以咱建议能提供一下类似于nginx的sub_filter功能：
```
location / {
sub_filter  'some.site.net' 'mydomain.com'; //替换目标网页内的some.site.net到mydomain.com
sub_filter_once off;   //替换所有的，默认是on，替换第一个
}
```

如果能实现这个功能，那么这个`masquerade: proxy`模式将更加强大，可玩性也将大大提高
