### ISSUE TITLE
[BUG] Userpass doesn't work if username contains uppercase letters

### ISSUE THREAD

**Issue by haruue** [apernet/hysteria#1297]
reported-by: @codetang-2417 
ref: https://github.com/apernet/hysteria/issues/1174#issuecomment-2579545354 https://github.com/apernet/hysteria/issues/1174#issuecomment-2580032296

## Reproduce

Server
```yaml
listen: :8443

tls:
  cert: /etc/hysteria/server.crt
  key: /etc/hysteria/server.key
  sniGuard: disable

auth:
  type: userpass
  userpass:
    user1: pass
    User2: pass
```

Client
```yaml
server: 127.0.0.1:8443

#auth: user1:pass
auth: User2:pass

tls:
  insecure: true

socks5:
  listen: 127.0.0.1:21080
```

When using `auth: user1:pass`, the Hysteria connection can be established, but it fails when using `auth: User2:pass`.

```
2025-01-09T21:40:54+09:00       FATAL   failed to initialize client     {"error": "authentication error, HTTP status code: 404"}
```

## Why?

Simply add a log here

```diff
diff --git a/app/cmd/server.go b/app/cmd/server.go
index 5f2d562..c4bf656 100644
--- a/app/cmd/server.go
+++ b/app/cmd/server.go
@@ -755,6 +755,7 @@ func (c *serverConfig) fillAuthenticator(hyConfig *server.Config) error {
                if len(c.Auth.UserPass) == 0 {
                        return configError{Field: "auth.userpass", Err: errors.New("empty auth userpass")}
                }
+               logger.Info("parsed userpass", zap.Any("userpass", c.Auth.UserPass))
                hyConfig.Authenticator = &auth.UserPassAuthenticator{Users: c.Auth.UserPass}
                return nil
        case "http", "https":
```

We will get

```
2025-01-09T21:44:58+09:00       INFO    parsed userpass {"userpass": {"user1":"pass","user2":"pass"}}
```

This issue is caused by viper, which silently converts all map keys to lower case (https://github.com/spf13/viper/issues/373), and there is still no option to disable this behavior.
