### ISSUE TITLE
connect error: timeout: no recent network activity

### ISSUE THREAD

**Issue by N214** [apernet/hysteria#1303]
Can someone help me, why am I getting this error? 
hysteria-client  | 2025-02-02T03:39:47Z FATAL   failed to initialize client     {"error": "connect error: timeout: no recent network activity"}

Using the same docker compose file, they share the network

config.yaml (server)
```yaml
listen: :443
tls:
  cert: /etc/hysteria/server.pem
  key: /etc/hysteria/server.key
  sniGuard: disable
auth:
  type: password
  password: toor
masquerade:
  type: proxy
  proxy:
    url: https://news.ycombinator.com/
    rewriteHost: true
```

client-config.yaml (client)
```yaml
server: 0.0.0.0:443
auth: toor
bandwidth:
  up: 10 mbps
  down: 20 mbps
socks5:
  listen: 127.0.0.1:10808
http:
  listen: 127.0.0.1:10809
udpForwarding:
  - listen: 127.0.0.1:1194
    remote: 127.0.0.1:1194
    timeout: 20s
```

docker-compose
```yaml
services:
  hysteria-server:
    image: 'tobyxdd/hysteria:latest'
    container_name: hysteria-server
    restart: always
    #network_mode: host
    ports:
      - "433:433"
    volumes:
      - '$PWD/:/etc/hysteria'
    environment:
      - HYSTERIA_DISABLE_UPDATE_CHECK = 1
      - HYSTERIA_LOG_LEVEL = debug
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
      - SYS_PTRACE
      - DAC_READ_SEARCH
    devices:
      - '/dev/net/tun:/dev/net/tun'
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    command: ["server", "-c", "/etc/hysteria/config.yaml"]
  hysteria-client:
    image: 'tobyxdd/hysteria:latest'
    container_name: hysteria-client
    restart: always
    #network_mode: host
    volumes:
      - '$PWD/:/etc/hysteria'
    environment:
      - HYSTERIA_DISABLE_UPDATE_CHECK = 1
      - HYSTERIA_LOG_LEVEL = debug
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
      - SYS_PTRACE
      - DAC_READ_SEARCH
    devices:
      - '/dev/net/tun:/dev/net/tun'
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    command: ["-c", "/etc/hysteria/client-config.yaml"]

```
