### ISSUE TITLE
Hot reload - reload config without making any interrupt connection

### ISSUE THREAD

**Issue by nickcarterney** [apernet/hysteria#1350]
I'm managing multiple users by using 

in /etc/hysteria/config.yaml
```
auth:
  type: userpass
  userpass:
    user1: pass1
    user2: pass2
    user3: pass3
```

The issue: when I trigger a restart of hysteria-server.service, the current connections will be interrupted.
`service hysteria-server restart`

Can you make a hot reload function or API to modify the userpass without reloading the configuration?
