### ISSUE TITLE
[功能请求] 在服务端使用DOH时可以添加解析DOH域名所用的DNS

### ISSUE THREAD

**Issue by fs8vsx59h** [apernet/hysteria#598]
### 功能描述

目前在服务端配置DNS时，可以配置DOH或者QUIC，在使用1.1.1.1的DOH服务时没有任何问题，这个DOH比较特殊，但大多数DOH都是使用域名的，如果仅在配置文件中的DNS中直接填写使用域名的DOH，hysteria将无法解析任何域名。   

是否可以在服务端使用DOH时添加解析DOH域名所用的DNS，例如配置文件中DNS部分如下
```json
 "resolver": ["udp://1.1.1.1:53","https://dns.nextdns.io"]
```
此时Hysteria将用第一个DNS服务器来解析后面DOH的域名，在进行代理时使用后面的DOH进行查询，第一个UDP plain dns仅用来解析DOH的域名。  

### 这个功能的必要性

如果不使用容器进行部署需要修改系统的host文件，或者安装其他DNS客户端（将DOH转为本地UDP plain DNS)，有些不方便。

### 当前可用的替代方案

我目前的解决方案是在docker-compose.yml文件中添加extra-host。docker compose 文件如下：  

```yaml
version: '3.9'
services:
  hysteria:
    image: tobyxdd/hysteria
    ...........................
    extra_hosts:
      - "dns.nextdns.io:45.90.28.202"

```
