### ISSUE TITLE
请问怎样配置国内域名不走代理

### ISSUE THREAD

**Issue by badongdyc** [apernet/hysteria#620]
如题

**Comment by wenpengHao** [comment]
direct country cn

**Comment by wenpengHao** [comment]
routes.acl 配置文件指定路由

**Comment by chucongqing** [comment]
我看文档客户端ACL还没做，可能需要本地跑个Server专门用来做ACL？

**Comment by us254** [comment]
```
acl:
  rules:
    - action: reject
      addr: ["geoip:cn", "10.0.0.0/8", "172.16.0.0/12"]
    - action: accept
      addr: ["192.168.0.0/16"]
    - action: reject
      addr: ["fc00::/7"]
      ```
