### ISSUE TITLE
[功能请求] hy2 服务端 ca: LetsEncrypt 参数示例层级

### ISSUE THREAD

**Issue by chika0801** [apernet/hysteria#627]
### 功能描述

参考文档 https://github.com/apernet/hysteria/blob/wip-hy2/app/server.example.yaml 这样写的
```
acme:
  domains:
    - 123.top
  email: chika@123.top
    ca: LetsEncrypt
```
报错 `failed to read server config	{"error": "While parsing config: yaml: line 7: mapping values are not allowed in this context"}`

问GPT改成下面的就行了

```
acme:
  domains:
    - 123.top
  email: chika@123.top
  ca: LetsEncrypt
```

### 这个功能的必要性

![屏幕截图 2023-06-25 155909](https://github.com/apernet/hysteria/assets/88967758/f1720ebc-bab8-4a31-a542-0f36d7421768)

示例的# 我觉得这样改下方便理解一点
```
acme:
  domains:
    - my.example.com
  email: hackerman@abcd.com
# ca: LetsEncrypt

```

**Comment by haruue** [comment]
yaml 的文档这样写确实比较迷惑。

行首加个 `#` 的话， 用户在删掉 `#` 之后还需要多补一个空格（或者用 vim 的 r）。

直接删掉 # 和 key 之间的空格会不会好一些？

```yaml
acme:
  domains:
    - my.example.com
  email: hackerman@abcd.com
  #ca: LetsEncrypt
  #disableHTTP: false
```

如果还是不行的话， 或许可以考虑把缩进改成 4 个 space ？

```yaml
acme:
    domains:
        - my.example.com
    email: hackerman@abcd.com
    #ca: LetsEncrypt
    #disableHTTP: false
```
