### ISSUE TITLE
[请求帮助] Hy2客户端配置 server: 填写 IPv6 地址时报错

### ISSUE THREAD

**Issue by chika0801** [apernet/hysteria#634]
### 问题详情

如下

server:  填IPv6地址时报错。如果填IPv4地址是能正常工作。

`{"error": "While parsing config: yaml: did not find expected key"}
Cannot mix synchronous and asynchronous operation on process stream.`

客户端配置

```
server: [2406:ef80:X:X::X]:443

auth: chika

tls:
  sni: lovelive123456.top

quic:
  initStreamReceiveWindow: 16777216
  maxStreamReceiveWindow: 16777216
  initConnReceiveWindow: 33554432
  maxConnReceiveWindow: 33554432
  maxIdleTimeout: 5s
  keepAlivePeriod: 3s

bandwidth:
  up: 50 mbps
  down: 300 mbps

fastOpen: true

socks5:
  listen: 127.0.0.1:10808
```
