### ISSUE TITLE
Hysteria 2.0，伪装网站无效

### ISSUE THREAD

**Issue by MarchGe** [apernet/hysteria#658]
**版本**
hysteria 2.0.0

**配置文件**
- 服务端配置
```yaml
listen: 0.0.0.0:12345
tls:
  cert: /PATH/cert.pem
  key: /PATH/cert.key
bandwidth: 
  up: 50m
  down: 10m
ignoreClientBandwidth: false
auth:
  type: password
  password: NmM2YzkwYzUtMGI2NC0
outbounds:
  - name: DEFAULT
    type: direct
masquerade:
  type: proxy
  proxy:
    url: https://MY-DOMAIN:8080
    rewriteHost: true
acl:
  inline:
    - reject(geosite:cn)
    - reject(geoip:cn)
    - direct(all)
```
- 客户端配置
```yaml
server: MY-DOMAIN:12345
auth: NmM2YzkwYzUtMGI2NC0
tls:
  sni: MY-DOMAIN
  insecure: false
  pinSHA256: E8:AA:B7:89:9B……
transport:
  type: udp
bandwidth:
  up: 10m
  down: 50m
fastOpen: false
lazy: true
http:
  listen: 127.0.0.1:1080
```

浏览器访问https://MY-DOMAIN:8080服务正常，访问https://MY-DOMAIN:12345，无法访问，提示如下：
> 无法访问此网站网址为 https://MY-DOMAIN:12345/ 的网页 可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_TUNNEL_CONNECTION_FAILED

**另外，再问个问题，2.0.0的client端不支持ACL吗？**
.
.
