### ISSUE TITLE
hy2.0不会用了,

### ISSUE THREAD

**Issue by f4nff** [apernet/hysteria#668]
hyv1:

```
{
	"listen": ":443",
  "protocol": "udp",
	"cert": "./my.crt",
	"key": "./my.key",
	"up_mbps": 200,
	"down_mbps": 200,
	"recv_window_conn": 671088640, 
	"recv_window_client": 671088640, 
	"max_conn_client": 65535
}

```

使用这样的配置文件,到hy2完全不行..

```
root@lp:~/hy# ./hysteria-linux-amd64 server
2023-09-08T00:18:23+08:00       INFO    server mode
2023-09-08T00:18:23+08:00       FATAL   failed to load server config    {"error": "invalid config: tls: must set either tls or acme"}
```

**Comment by f4nff** [comment]
server:

```
listen: :443

tls:
  cert: /root/hy/api.hisdk.com.cer
  key: /root/hy/api.hisdk.com

auth:
  type: password
  password: gnxMEu8zV5XMPTv9

bandwidth:
  up: 200 mbps
  down: 200 mbps
  
quic:
  initStreamReceiveWindow: 8388608 
  maxStreamReceiveWindow: 8388608 
  initConnReceiveWindow: 20971520 
  maxConnReceiveWindow: 20971520 
  maxIdleTimeout: 30s 
  keepAlivePeriod: 10s 
  disablePathMTUDiscovery: false 

```


client:
```

server: api.hisdk.com:443

auth: gnxMEu8zV5XMPTv9

bandwidth:
  up: 100 mbps
  down: 200 mbps

socks5:
  listen: 0.0.0.0:1080


```


总算测试通过.

不能跳过证书验证?

没有tun模式, 怎么路由器使用?

**Comment by f4nff** [comment]
```
listen: :443

tls:
  cert: /root/hy/ldsdk.com.cer
  key: /root/hy/ldsdk.com.key

auth:
  type: password
  password: gnxMEu8zV5XMPTv9

bandwidth:
  up: 200 mbps
  down: 200 mbps
  

quic:
  initStreamReceiveWindow: 26843545 
  maxStreamReceiveWindow: 26843545 
  initConnReceiveWindow: 67108864 
  maxConnReceiveWindow: 67108864 
  maxIdleTimeout: 30s 
  keepAlivePeriod: 10s 
  disablePathMTUDiscovery: false 

log:
  HYSTERIA_LOG_LEVEL: error
  HYSTERIA_DISABLE_UPDATE_CHECK: 1
  
```


日志格式没有静默运行?  任何都不输出.

**Comment by f4nff** [comment]
```
transport:
  udp:
    hopInterval: 30s 
```

客户端跳跃,

`
server: api.ldsdk.com:443`

服务端如果只监听一个端口,应该也可实现客户端跳跃.
这样本地发起端口就变了.

**Comment by f4nff** [comment]
v2总结如下:
1:不支持tun模式,
2:客户端跳跃不支持服务端只监听一个端口,
3:服务端不支持监听多端口
4:日志没有静默输出选项.
5:客户端没有跳过证书验证

**Comment by f4nff** [comment]
server:

```
listen: :443


tls:
  cert: /root/hy/ldsdk.com.cer
  key: /root/hy/ldsdk.com.key

auth:
  type: password
  password: gnxMEu8zV5XMPTv9

bandwidth:
  up: 200 mbps
  down: 200 mbps
  ignoreClientBandwidth: false
  disableUDP: false
  udpIdleTimeout: 5s
  

quic:
  initStreamReceiveWindow: 26843545 
  maxStreamReceiveWindow: 26843545 
  initConnReceiveWindow: 67108864 
  maxConnReceiveWindow: 67108864 
  maxIdleTimeout: 30s 
  keepAlivePeriod: 10s 
  disablePathMTUDiscovery: false 
  
  

log:
  HYSTERIA_LOG_LEVEL: error
  HYSTERIA_DISABLE_UPDATE_CHECK: 1
  
```


client:

```

server: 15.16.72.36:443

auth: gnxMEu8zV5XMPTv9

bandwidth:
  up: 100 mbps
  down: 200 mbps

socks5:
  listen: 0.0.0.0:1080

log:
  HYSTERIA_LOG_LEVEL: error
  HYSTERIA_DISABLE_UPDATE_CHECK: 1
  


transport:
  udp:
    hopInterval: 30s
    
    
tls:
  insecure: true

quic:
  initStreamReceiveWindow: 26843545 
  maxStreamReceiveWindow: 26843545 
  initConnReceiveWindow: 67108864 
  maxConnReceiveWindow: 67108864 
  maxIdleTimeout: 30s 
  keepAlivePeriod: 10s 
  disablePathMTUDiscovery: false 
  
```
