### ISSUE TITLE
hysteria2连不上并报错，hysteria1正常，服务器，PC，网络都相同

### ISSUE THREAD

**Issue by zazi0001** [apernet/hysteria#685]
日志：
2023-09-13T13:56:32+08:00	[31mERROR[0m	SOCKS5 TCP error	{"addr": "127.0.0.1:56137", "reqAddr": "optimizationguide-pa.googleapis.com:443", "error": "connect error: timeout: no recent network activity"}
2023-09-13T13:59:32+08:00	[31mERROR[0m	SOCKS5 TCP error	{"addr": "127.0.0.1:56182", "reqAddr": "optimizationguide-pa.googleapis.com:443", "error": "connect error: timeout: no recent network activity"}
2023-09-13T14:01:12+08:00	[31mERROR[0m	SOCKS5 TCP error	{"addr": "127.0.0.1:56219", "reqAddr": "clients4.google.com:443", "error": "connect error: timeout: no recent network activity"}
2023-09-13T14:02:16+08:00	[31mERROR[0m	SOCKS5 TCP error	{"addr": "127.0.0.1:56239", "reqAddr": "optimizationguide-pa.googleapis.com:443", "error": "connect error: timeout: no recent network activity"}
2023-09-13T14:03:36+08:00	[31mERROR[0m	SOCKS5 TCP error	{"addr": "127.0.0.1:56258", "reqAddr": "mtalk.google.com:5228", "error": "connect error: timeout: no recent network activity"}
2023-09-13T14:05:01+08:00	[31mERROR[0m	SOCKS5 TCP error	{"addr": "127.0.0.1:56281", "reqAddr": "optimizationguide-pa.googleapis.com:443", "error": "connect error: timeout: no recent network activity"}
2023-09-13T14:07:31+08:00	[31mERROR[0m	SOCKS5 TCP error	{"addr": "127.0.0.1:56322", "reqAddr": "optimizationguide-pa.googleapis.com:443", "error": "connect error: timeout: no recent network activity"}
2023-09-13T14:10:30+08:00	[31mERROR[0m	SOCKS5 TCP error	{"addr": "127.0.0.1:56368", "reqAddr": "optimizationguide-pa.googleapis.com:443", "error": "connect error: timeout: no recent network activity"}
2023-09-13T14:11:17+08:00	[31mERROR[0m	SOCKS5 TCP error	{"addr": "127.0.0.1:56383", "reqAddr": "clients4.google.com:443", "error": "connect error: timeout: no recent network activity"}
2023-09-13T14:13:25+08:00	[31mERROR[0m	SOCKS5 TCP error	{"addr": "127.0.0.1:56418", "reqAddr": "optimizationguide-pa.googleapis.com:443", "error": "connect error: timeout: no recent network activity"}
2023-09-13T14:13:41+08:00	[31mERROR[0m	SOCKS5 TCP error	{"addr": "127.0.0.1:56423", "reqAddr": "mtalk.google.com:443", "error": "connect error: timeout: no recent network activity"}
panic: connection already exists
goroutine 5100 [running]:
github.com/apernet/quic-go.(*connMultiplexer).AddConn(0xc00007ff80, {0x20866d05e30?, 0xc000386180?})
	github.com/apernet/quic-go@v0.38.2-0.20230902022200-c0e542a00ce6/multiplexer.go:59 +0x165
github.com/apernet/quic-go.(*Transport).init.func1()
	github.com/apernet/quic-go@v0.38.2-0.20230902022200-c0e542a00ce6/transport.go:214 +0x332
sync.(*Once).doSlow(0x208673a11c0?, 0x1496a40?)
	sync/once.go:74 +0xbf
sync.(*Once).Do(...)
	sync/once.go:65
github.com/apernet/quic-go.(*Transport).init(0xc00024e000, 0x5d?)
	github.com/apernet/quic-go@v0.38.2-0.20230902022200-c0e542a00ce6/transport.go:181 +0x4d
github.com/apernet/quic-go.(*Transport).dial(0xc00024e000, {0x1623150, 0x1ac1ce0}, {0x161fd10, 0xc000089a40}, {0x0, 0x0}, 0xc00034d968?, 0xdc0805?, 0x1)
	github.com/apernet/quic-go@v0.38.2-0.20230902022200-c0e542a00ce6/transport.go:167 +0xa5
github.com/apernet/quic-go.(*Transport).DialEarly(...)
	github.com/apernet/quic-go@v0.38.2-0.20230902022200-c0e542a00ce6/transport.go:159
github.com/apernet/quic-go.DialEarly({0x1623150, 0x1ac1ce0}, {0x1625c50?, 0xc000386180?}, {0x161fd10, 0xc000089a40}, 0xc0002621a0, 0x14ca4e0?)
	github.com/apernet/quic-go@v0.38.2-0.20230902022200-c0e542a00ce6/client.go:95 +0x127
github.com/apernet/hysteria/core/client.(*clientImpl).connect.func1({0x1623150?, 0x1ac1ce0?}, {0xc00034da00?, 0xc00034d9d0?}, 0x3?, 0x8?)
	github.com/apernet/hysteria/core/client/client.go:88 +0x4d
github.com/apernet/quic-go/http3.(*client).dial(0xc0002ca200, {0x1623150, 0x1ac1ce0})
	github.com/apernet/quic-go@v0.38.2-0.20230902022200-c0e542a00ce6/http3/client.go:122 +0x67
github.com/apernet/quic-go/http3.(*client).RoundTripOpt.func1()
	github.com/apernet/quic-go@v0.38.2-0.20230902022200-c0e542a00ce6/http3/client.go:262 +0x49
sync.(*Once).doSlow(0x151609a?, 0x5?)
	sync/once.go:74 +0xbf
sync.(*Once).Do(...)
	sync/once.go:65
github.com/apernet/quic-go/http3.(*client).RoundTripOpt(0xc0002ca200, 0xc00018ea00, {0xc?, 0x0?})
	github.com/apernet/quic-go@v0.38.2-0.20230902022200-c0e542a00ce6/http3/client.go:261 +0xed
github.com/apernet/quic-go/http3.(*RoundTripper).RoundTripOpt(0xc000008798?, 0xc00018ea00, {0x40?, 0x9a?})
	github.com/apernet/quic-go@v0.38.2-0.20230902022200-c0e542a00ce6/http3/roundtrip.go:150 +0x50e
github.com/apernet/quic-go/http3.(*RoundTripper).RoundTrip(...)
	github.com/apernet/quic-go@v0.38.2-0.20230902022200-c0e542a00ce6/http3/roundtrip.go:164
github.com/apernet/hysteria/core/client.(*clientImpl).connect(0xc000336090)
	github.com/apernet/hysteria/core/client/client.go:110 +0x339
github.com/apernet/hysteria/core/client.NewClient(0xc0000ca370)
	github.com/apernet/hysteria/core/client/client.go:44 +0x5c
github.com/apernet/hysteria/core/client.(*reconnectableClientImpl).reconnect(0xc000089a80)
	github.com/apernet/hysteria/core/client/reconnect.go:45 +0x45
github.com/apernet/hysteria/core/client.(*reconnectableClientImpl).TCP(0xc000089a80, {0xc00002c3c0, 0x27})
	github.com/apernet/hysteria/core/client/reconnect.go:65 +0xbb
github.com/apernet/hysteria/app/internal/socks5.(*Server).handleTCP(0xc000486390, {0x1626708?, 0xc000480000}, 0xdf515c?)
	github.com/apernet/hysteria/app/internal/socks5/server.go:138 +0x1c2
github.com/apernet/hysteria/app/internal/socks5.(*Server).dispatch(0xc000486390, {0x1626708, 0xc000480000})
	github.com/apernet/hysteria/app/internal/socks5/server.go:54 +0xee
created by github.com/apernet/hysteria/app/internal/socks5.(*Server).Serve in goroutine 38
	github.com/apernet/hysteria/app/internal/socks5/server.go:36 +0x2c

**Comment by zazi0001** [comment]
场景是开了俩浏览器分别挂着俩代理，hysteria2用V2rayN启动，hyseria1用命令行，出去吃个饭回来hysteria2出现问题

**Comment by tobyxdd** [comment]
发一下服务端和客户端配置，删掉敏感信息 但是要包括有没有用端口跳跃之类的

**Comment by tobyxdd** [comment]
这个问题是偶然出现还是能稳定复现？

**Comment by zazi0001** [comment]
服务端配置：
listen: :12345
tls:
  cert: /path/to/crt
  key: /path/to/key
quic:
  initStreamReceiveWindow: 8388608 
  maxStreamReceiveWindow: 8388608 
  initConnReceiveWindow: 20971520 
  maxConnReceiveWindow: 20971520 
  maxIdleTimeout: 30s 
  maxIncomingStreams: 1024 
  disablePathMTUDiscovery: false 
ignoreClientBandwidth: false
disableUDP: false
obfs:
  type: salamander
  salamander:
    password: obfs_password
udpIdleTimeout: 60s
auth:
  type: userpass
  userpass: 
    user1: 123
    user2: 456
masquerade:
  type: proxy
  proxy:
    url: https://www.bing.com/
    rewriteHost: true 
resolver:
  type: tls
  udp:
    addr: 8.8.4.4:53 
    timeout: 4s
  tls:
    addr: 1.1.1.1:853 
    timeout: 10s
    sni: cloudflare-dns.com 
    insecure: false 
客户端配置：
server: xxx.xxx.xxx:12345
auth: user1:123
obfs:
  type: salamander
  salamander:
    password: obfs_password
transport:
  type: udp
  udp:
    hopInterval: 30s 
quic:
  initStreamReceiveWindow: 8388608 
  maxStreamReceiveWindow: 8388608 
  initConnReceiveWindow: 20971520 
  maxConnReceiveWindow: 20971520 
  maxIdleTimeout: 30s 
  keepAlivePeriod: 10s 
  disablePathMTUDiscovery: false
fastOpen: true
socks5:
  listen: 127.0.0.1:1080

**Comment by zazi0001** [comment]
这个问题是偶然发生的，我尝试复现

**Comment by zazi0001** [comment]
> 发一下服务端和客户端配置，删掉敏感信息 但是要包括有没有用端口跳跃之类的

服务端配置：  
`iptables -t nat -A PREROUTING -i eth0 -p udp --dport 43000:50000 -j DNAT --to-destination :12345`
```
listen: :12345
tls:
  cert: /path/to/crt
  key: /path/to/key
quic:
  initStreamReceiveWindow: 8388608 
  maxStreamReceiveWindow: 8388608 
  initConnReceiveWindow: 20971520 
  maxConnReceiveWindow: 20971520 
  maxIdleTimeout: 30s 
  maxIncomingStreams: 1024 
  disablePathMTUDiscovery: false 
ignoreClientBandwidth: false
disableUDP: false
obfs:
  type: salamander
  salamander:
    password: obfs_password
udpIdleTimeout: 60s
auth:
  type: userpass
  userpass: 
    user1: 123
    user2: 456
masquerade:
  type: proxy
  proxy:
    url: https://www.bing.com/
    rewriteHost: true 
resolver:
  type: tls
  udp:
    addr: 8.8.4.4:53 
    timeout: 4s
  tls:
    addr: 1.1.1.1:853 
    timeout: 10s
    sni: cloudflare-dns.com 
    insecure: false
```
客户端配置：
```
server: xxx.xxx.xxx:12345
auth: user1:123
obfs:
  type: salamander
  salamander:
    password: obfs_password
transport:
  type: udp
  udp:
    hopInterval: 30s 
quic:
  initStreamReceiveWindow: 8388608 
  maxStreamReceiveWindow: 8388608 
  initConnReceiveWindow: 20971520 
  maxConnReceiveWindow: 20971520 
  maxIdleTimeout: 30s 
  keepAlivePeriod: 10s 
  disablePathMTUDiscovery: false
fastOpen: true
socks5:
  listen: 127.0.0.1:1080
```
