### ISSUE TITLE
在未指定配置文件路径时， 默认配置文件选择不正确

### ISSUE THREAD

**Issue by BrightVan** [apernet/hysteria#689]
客户端连接报错：failed to initialize client (authentication error, HTTP status code: 404)，没有使用默认的443端口，自定义端口是放开的，但客户端连不上，搞不清楚原因

使用docker 部署，
```yml
version: "3.9"
services:
  hysteria:
    image: tobyxdd/hysteria
    container_name: hysteria
    restart: always
    network_mode: "host"
    volumes:
      - ./hysteria.yaml:/etc/hysteria.yaml
      - /etc/acme/mydomain/:/etc/acme/mydomain/
    command: ["server", "-c", "/etc/hysteria.yaml"]
```
docker logs:
```
# docker logs hysteria
2023-09-14T08:28:07Z    INFO    server mode
2023-09-14T08:28:07Z    INFO    server up and running
```
服务端配置：

```yaml
listen: :12345 

tls:
  cert: /etc/acme/mydomain/fullchain.pem 
  key: /etc/acme/mydomain/privkey.pem

auth:
  type: password
  password: mypassword 

masquerade: 
  type: proxy
  proxy:
    url: https://news.ycombinator.com/ 
    rewriteHost: true
```
客户端配置：
```yaml
server: mydomain:12345
 
auth: mypassword
 
bandwidth: 
  up: 20 mbps
  down: 100 mbps
 
socks5:
  listen: 127.0.0.1:8889 
 
http:
  listen: 127.0.0.1:8888 
```
