### ISSUE TITLE
ACME证书申请方式增加DNS验证方式

### ISSUE THREAD

**Issue by joyoner** [apernet/hysteria#750]
**你的功能请求是否与某个问题有关？**
对于80/443端口已经被占用的设备，目前使用ACME申请证书存在不便。

**描述你希望的解决方案**
支持ACME的DNS验证方式来申请证书。

**有没有其他替代方案**
暂无

**额外信息**
通过CloudFlare DNS验证示例，
cert_domain=xxx.com
cert_mode=dns
cert_key_length=ec-256
dns_provider=dns_cf
DNS_CF_Email=xxx@xx.com
DNS_CF_Key=xxxxx

**Comment by haruue** [comment]
每个 DNS 提供商都需要各自的调用 DNS API 的实现（参考 caddy 和 libdns 的做法）以及各自的配置。

caddy 用插件化实现了这一点， 而这也导致它需要 xcaddy 以及 https://caddyserver.com/download 这种定制下载工具。

如果 hysteria 要支持的话， 我觉得或许可以考虑只在官方 release 中支持几个比较常用的 DNS 提供商。

**Comment by joyoner** [comment]
静候CloudFlare DNS方式:)

**Comment by tomxiang1** [comment]
acme脚本已经很强大了，看一下教程就搞定了，何必重复造轮子。

**Comment by JsonSong89** [comment]
acme成熟项目大把,最好还是用两个流程串起来吧
hy直接用本地证书文件

**Comment by mritd** [comment]
如果增加 DNS 挑战的话, 可能需要对现有配置文件结构进行修改; 会有不兼容变动; 比如现有结构:

```yaml
acme:
  domains:
    - domain1.com
    - domain2.org
  email: your@email.net
  ca: zerossl 
  disableHTTP: false 
  disableTLSALPN: false 
  altHTTPPort: 8080 
  altTLSALPNPort: 4443 
  dir: my_acme_dir 
```

**当前是支持多域名配置的, DNS API 需要明确知道哪个域名使用哪个 DNS API 来完成证书申请.**
