### ISSUE TITLE
我出站设置了一个远程的socks5代理，具备身份验证，链接后显示unknown port

### ISSUE THREAD

**Issue by B1gCarr0t** [apernet/hysteria#761]
通过ACL配置了分流组
在出站填写了分流规则类型是socks5
addr："远程IP:端口, id=1, username=巴拉巴拉, password=巴拉巴拉"
查看状态返回了：{"addr": "我的IP:随机端口", "id": "user", "reqAddr": "目标地址:443", "error": "dial tcp: address tcp/58835, id=1, username=巴拉巴拉, password=巴拉巴拉: **unknown port**"}
socks5的服务端已经启用，防火墙也已经放行，请问是无法设置远程代理，还是我的addr填写格式有问题？

**Comment by haruue** [comment]
addr 只写 IP 和端口， 用户名密码是单独的字段。 类似于下面这样。

```yaml
outbounds:
  - name: my_outbound_2
    type: socks5
    socks5:
      addr: 远程IP:端口 
      username: 巴拉巴拉 
      password: 巴拉巴拉 
```

你给的例子里的 id 不是标准字段。 不知道是干啥的。
