### ISSUE TITLE
masquerade proxy 无法正确处理 ws 请求

### ISSUE THREAD

**Issue by doveccl** [apernet/hysteria#780]
**描述问题**
proxy 普通 http 协议正常，ws 失败
秉承“做戏做全套”原则，希望作者大大支持一下

**如何复现**
```yaml
masquerade:
  listenHTTP: :80
  listenHTTPS: :443
  forceHTTPS: true
  type: proxy
  proxy:
    url: http://127.0.0.1:8000 # 本地 8000 端口有 ws 服务
```

**日志**
```
ERROR   HTTP reverse proxy error        {"error": "can't switch protocols using non-Hijacker ResponseWriter type *masq.altSvcHijackResponseWriter"}
```
