### ISSUE TITLE
使用 docker compose 部署了 hysteria2 容器，但无法正常使用

### ISSUE THREAD

**Issue by leic4u** [apernet/hysteria#781]
**描述问题**
使用 docker compose 部署了 hysteria2 容器，但无法正常使用。

访问 `我的域名` 没有显示伪装网站 `https://microsoft-update.com`。

tcping `我的域名:443` 也失败。

客户端使用 clash.meta v1.16.0 连接也失败。

docker-compose.yml：
```
version: "3.9"
services:
  hysteria:
    image: tobyxdd/hysteria
    container_name: hysteria2
    restart: always
    network_mode: "host"
    volumes:
      - ./acme:/acme
      - ./hysteria.yaml:/etc/hysteria.yaml
    command: ["server", "-c", "/etc/hysteria.yaml"]
volumes:
  acme:
```

服务端配置：
```
listen: :443 #监听端口

acme:
  domains:
    - 我的域名
  email: isjqusg@outlook.com
  ca: zerossl

bandwidth:
  up: 120 mbps
  down: 500 mbps

auth:
  type: password
  password: Zski2iD #设置认证密码

masquerade:
  type: proxy
  proxy:
    url: https://microsoft-update.com #伪装网址
    rewriteHost: true
```

clash.meta 1.16 配置
```
  - name: hysteria2-proxy
    type: hysteria2
    server: 我的域名
    port: 443
    #  up和down均不写或为0则使用BBR流控
    up: 120 Mbps # 若不写单位，默认为 Mbps
    down: 500 Mbps # 若不写单位，默认为 Mbps
    password: Zski2iD 
```

**如何复现**
按以上步骤部署容器

**预期行为**
访问 `我的域名` ，应该可以正常访问伪装网站 `https://microsoft-update.com`

**日志**
容器日志
```
2023-10-28T18:17:34Z    INFO    server mode
2023-10-28T18:17:35Z    INFO    maintenance     started background certificate maintenance      {"cache": "0xc000114c40"}
2023-10-28T18:17:35Z    INFO    obtain  acquiring lock  {"identifier": "我的域名"}
2023-10-28T18:17:35Z    INFO    obtain  lock acquired   {"identifier": "我的域名"}
2023-10-28T18:17:35Z    INFO    obtain  obtaining certificate   {"identifier": "我的域名"}
2023-10-28T18:17:37Z    INFO    waiting on internal rate limiter        {"identifiers": ["我的域名"], "ca": "https://acme.zerossl.com/v2/DV90", "account": "isjqusg@outlook.com"}
2023-10-28T18:17:37Z    INFO    done waiting on internal rate limiter   {"identifiers": ["我的域名"], "ca": "https://acme.zerossl.com/v2/DV90", "account": "isjqusg@outlook.com"}
2023-10-28T18:17:38Z    INFO    acme_client     trying to solve challenge       {"identifier": "我的域名", "challenge_type": "http-01", "ca": "https://acme.zerossl.com/v2/DV90"}
2023-10-28T18:17:40Z    INFO    served key authentication       {"identifier": "我的域名", "challenge": "http-01", "remote": "91.199.212.132:42634", "distributed": false}
2023-10-28T18:17:45Z    INFO    acme_client     authorization finalized {"identifier": "我的域名", "authz_status": "valid"}
2023-10-28T18:17:45Z    INFO    acme_client     validations succeeded; finalizing order {"order": "https://acme.zerossl.com/v2/DV90/order/hSRGAhqn8p4N_****"}
2023-10-28T18:18:01Z    INFO    acme_client     successfully downloaded available certificate chains    {"count": 1, "first_url": "https://acme.zerossl.com/v2/DV90/cert/ETQJu2B8FD94yq****"}
2023-10-28T18:18:01Z    INFO    obtain  certificate obtained successfully       {"identifier": "我的域名"}
2023-10-28T18:18:01Z    INFO    obtain  releasing lock  {"identifier": "我的域名"}
2023-10-28T18:18:02Z    INFO    server up and running
2023-10-28T18:22:31Z    INFO    server mode
2023-10-28T18:22:32Z    INFO    maintenance     started background certificate maintenance      {"cache": "0xc0000f3650"}
2023-10-28T18:22:32Z    INFO    server up and running
2023-10-28T18:38:56Z    INFO    server mode
2023-10-28T18:38:58Z    INFO    maintenance     started background certificate maintenance      {"cache": "0xc0000d5960"}
2023-10-28T18:38:58Z    INFO    server up and running
2023-10-28T18:40:32Z    INFO    server mode
2023-10-28T18:40:34Z    INFO    server up and running
2023-10-28T18:40:34Z    INFO    maintenance     started background certificate maintenance      {"cache": "0xc000124070"}

**设备和操作系统**
服务端 ubuntu 20.04 docker

**额外信息**
其他你认为有助于解决问题的信息。
