### ISSUE TITLE
Configured ACL not working.

### ISSUE THREAD

**Issue by vahidx4r4x** [apernet/hysteria#799]
Hi,
I just configured my Hysteria2 server file and activated the ACL function. I want to forward all the traffic from `google` to warp proxy on my server. but when I am checking my ip on google it is showing my real IP Address.

my server config:
```
listen: :443

tls:
  cert: /root/cert.crt
  key: /root/private.key

quic:
  initStreamReceiveWindow: 16777216
  maxStreamReceiveWindow: 16777216
  initConnReceiveWindow: 33554432
  maxConnReceiveWindow: 33554432

auth:
  type: password
  password: password

masquerade:
  type: proxy
  file:
   dir: /var/www/html
  proxy:
    url: https://URL.com
    rewriteHost: true
  #listenHTTP: :80
  #listenHTTPS: :443
  #forceHTTPS: true

acl:
  inline:
    #geoip: geoip.dat
    #geosite: geosite.dat
  - warp(geosite:netflix)
  - warp(geosite:google)
  - warp(geosite:facebook)
  - warp(geosite:meta)
  - reject(geoip:cn)
  - reject(geoip:kp)
  - reject(geosite:google@ads)
  - direct(all)
  
outbounds:
  - name: direct
    type: direct

  - name: warp
    type: socks5
    socks5:
      addr: 127.0.0.1:40000
```
hysteria service is up and running
warp proxy service is up and running and listening on 127.0.0.1:40000

What is wrong with it?

Ubuntu 20.04 AMD64

**Comment by tobyxdd** [comment]
Check if your requests were made with domain or IP. GeoSite is a domain list and cannot be matched against IP addresses.

**Comment by vahidx4r4x** [comment]
> Check if your requests were made with domain or IP. GeoSite is a domain list and cannot be matched against IP addresses.

hey,
how can i check the requests?

**Comment by tobyxdd** [comment]
It should work. What error did you get?

**Comment by wenpengHao** [comment]
Running into the same issue
Tried different rules repeatedly deubg, and found that geosite:facebook is effective when the client uses the http proxy

For example
warp(ipinfo.io)
reject(geosite:facebook)
reject(geoip:facebook)

Use HTTP Proxy
curl -v -x http://127.0.0.1:35181 https://ipinfo.io

2023-11-05T18:15:02+08:00 DEBUG TCP request {"addr": "223.74.158.154:10320", "id": "user", "reqAddr": "ipinfo.io:443"}
2023-11-05T18:15:02+08:00 DEBUG TCP closed {"addr": "223.74.158.154:10320", "id": "user", "reqAddr": "ipinfo.io:443"}

Use socks5
curl -v -x socks5://127.0.0.1:35180 https://ipinfo.io

2023-11-05T18:18:04+08:00 DEBUG TCP request {"addr": "223.74.158.154:10474", "id": "user", "reqAddr": "34.117.59.81:443"}
2023-11-05T18:18:05+08:00 DEBUG TCP closed {"addr": "223.74.158.154:10474", "id": "user", "reqAddr": "34.117.59.81: 443"}

At present, it is believed that the cause is the lack of domain name resolution and IP mapping
----------------------------------------------------------------
In addition, it is occasionally found that some domain names use local outdated DNS, and some domain names cannot be accessed, which is solved by modifying the CDN IP.
Can I use Remote DNS to resolve client domain names? Didn't find where the configuration is

**Comment by MintOcha** [comment]
> > Check if your requests were made with domain or IP. GeoSite is a domain list and cannot be matched against IP addresses.
> 
> hey, thanks, I added a `- warp(geoip:google)` to the ACL rules and it did work. one more question: How can I specify `.dat` file to the config? cuz I want to add more rules from a `.dat` file. I downloaded `geosite.dat` and `geoip.dat` and specified the directory in `config.yaml` but it returned an error. so I commented them in config file to force hysteria download them.

if you want to block google you should be using `- warp(geosite:google)`

**Comment by yarmetrepo** [comment]
Hi, I run Hysteria2 in a docker container. Here is my hysteria.yaml
```yaml
tls:
  cert: /path/to/cert.crt
  key:/path/to/private.key

auth:
  type: password
  password: mypasswd

acl:
  inline:
    - warp(geosite:openai)
    - direct(all)

outbounds:
  - name: warp
    type: socks5
    socks5:
      addr: warp:1080
```
If I run hysteria container as root. It works well. the teosinte.dat is downloaded at /geosite.dat.
```shell
$ docker exec -it hysteria sh
/ # ls -l /geosite.dat
-rw-r--r--    1 root     root       5244845 Nov 28 00:04 /geosite.dat
/ # ls -ld /
drwxr-xr-x    1 root     root          4096 Nov 28 00:04 /
```
I want run container as non-root user.  Can I config the path in the container to download geosite.dat ?
Non-root user doesn't have right to writre at path ```/``` in the container.
