### ISSUE TITLE
DNS解析

### ISSUE THREAD

**Issue by ibinlike** [apernet/hysteria#807]
**描述问题**

因为使用奈法DNS解析服务， 所以在服务器端设置了DNS解析地址： 

```
listen: :8088

tls:
  sni: www.bing.com
  insecure: true
  cert: /root/fullchain.cer
  key: /root/private.key




auth:
  type: password
  password: aaaaaaaaaaaaaaaaaaaaaa

resolver:
  type: udp
  udp:
    addr: x.x.x.x:53 (奈法DNS解锁服务器地址）
    timeout: 10s

```

但是在设置以后， 任何外网都无法访问。 

**如何复现**
1. 将DNS地址设置为 1.1.1.1， 外网可以访问
2. 配制文件删除resolver的配制， 外网可以访问
3. 使用echo -e "nameserver x.x.x.x(奈法dns解锁服务器地址） " > /etc/resolv.conf， 外网可以访问， 奈法DNS解锁成功。

**预期行为**
DNS解析成功

**日志**
附上客户端/服务器端在错误发生前后的日志。

**设备和操作系统**
软路由：passwall， 服务器： Debian 12

**额外信息**
其他你认为有助于解决问题的信息。

配制奈法解锁服务器地址的时候的日志：
![Xnip2023-11-09_10-48-03](https://github.com/apernet/hysteria/assets/12690686/266b8ca4-a8d9-48c3-a84d-f8f930732efa)
