### ISSUE TITLE
I can't use multi-user.

### ISSUE THREAD

**Issue by Haicaji** [apernet/hysteria#824]
```yaml
auth:
  type: password
  password: your_password 
  userpass: 
    user1: pass1
    user2: pass2
    user3: pass3
  http:
    url: http://your.backend.com/auth 
    insecure: false 
  command: /etc/some_command
```

But according to the above configuration, it is not possible to achieve multiple users.
I think it's a configuration issue with my client. Does anyone know what to do?

**Comment by haruue** [comment]
https://hysteria.network/docs/advanced/Full-Server-Config/
> **NOTE:** One common pattern you'll encounter in both the client & server configurations is the "type selector":
>
> ```yaml
> example:
>   type: a
>   a:
>     something: something
>   b:
>     something: something
>   c:
>     something: something
> ```

In other words, if you want to use `userpass` authentication, the actual configuration should be:

```yaml
auth:
  type: userpass # <- this selects the userpass authentication
  userpass:
    user1: pass1
    user2: pass2
    user3: pass3
```
