### ISSUE TITLE
Docker部署 Hysteria2,客户端V2rayN无法连接

### ISSUE THREAD

**Issue by Administrator404** [apernet/hysteria#859]
**描述问题**
Docker部署 Hysteria2,客户端V2rayN无法连接。

**如何复现**
客户端配置
```yaml
server: 111.111.111.111:443
auth: 111

bandwidth:
  up: 100 mbps
  down: 100 mbps
  
tls:
  sni: xxx.com
  insecure: false #使用自签时需要改成true

socks5:
  listen: 127.0.0.1:1080
http:
  listen: 127.0.0.1:8080
```
服务端配置
```yaml
listen: :443 
tls:
  cert: /etc/hysteria/xxx.com.crt
  key: /etc/hysteria/xxx.com.key

auth:
  type: password
  password: 111
```
docker-compose.yaml
```yaml
version: "3.9"
services:
  hysteria:
    image: tobyxdd/hysteria
    container_name: hysteria
    restart: always
    network_mode: "host"
    volumes:
      - acme:/acme
      - /etc/hysteria:/etc/hysteria
    command: ["server", "-c", "/etc/hysteria/hysteria.yaml"]
volumes:
  acme:
```
启动命令
```bash
docker-compose up -d
```

**预期行为**
可以正常连接使用

**日志**
服务端日志
![image](https://github.com/apernet/hysteria/assets/48144002/b7ee10c0-e860-4fe3-b11e-87f5c926b834)
客户端日志
![image](https://github.com/apernet/hysteria/assets/48144002/bf7f54e8-c4a6-4254-a121-40b1586808c7)

**设备和操作系统**
Centos 7.9 - x86_64

**额外信息**
启动后端口监听情况
![image](https://github.com/apernet/hysteria/assets/48144002/e4146b3b-89c7-4b65-b1fb-5c8fbec3195e)
