### ISSUE TITLE
请问当前能否使用ACL将网站重定向到本机（服务端）中的web应用

### ISSUE THREAD

**Issue by Dnife** [apernet/hysteria#883]
我使用docker在hysteria2同一服务器上部署了一个web应用。
该应用可通过80端口从站外正常访问。

请问能否通过使用ACL将特定地址劫持到本机web应用上？
这样web应用就仅向连接此服务器的人公开。
我目前的服务器配置如下，

```
listen: :10000

tls:
  cert: /home/ubuntu/ca/server.crt
  key: /home/ubuntu/ca/server.key 

auth:
  type: password
  password: Password

acl:
  inline:
    - hijack(suffix:baidu.com,*,127.0.0.1)

outbounds:
  - name: hijack
    type: direct

```
允许服务器的本机访问
`sudo iptables -A INPUT -s 127.0.0.1 -d 127.0.0.1 -j ACCEPT`

经过测试，重定向可正确指向本机web应用，但后续无法正常使用web应用。
日志中也没有报错信息。

请问您是否知道造成此现象的原因，是否有解决办法？
