### ISSUE TITLE
关于docker部署情况下证书申请的问题

### ISSUE THREAD

**Issue by toyo2333** [apernet/hysteria#885]
我的机器上也在用xray，并且是全docker部署，我没有使用host网络模式

```
    xray:
        image: teddysun/xray:1.8.4
        container_name: xray
        restart: unless-stopped
        logging:
            options:
                max-size: 10m
        ports:
            - "443:443"
        volumes:
            - ./xray:/etc/xray

    hysteria:
        image: tobyxdd/hysteria
        container_name: hysteria
        restart: always
        ports:
        #    - "80:80"
        #    - "443:443"
           - "443:443/udp"
        volumes:
        - acme:/acme
        - ./hys/hysteria.yaml:/etc/hysteria.yaml
        command: ["server", "-c", "/etc/hysteria.yaml"]
```
部署步骤：

1、我在启动之前，先注释掉xray，然后把hys2的端口80 443 udp443全映射，然后启动完成证书申请
2、然后恢复xray，并注释掉hys2的tcp80和443只保留udp443.
最终：——这样这两个代理服务的就可以共存使用。

我的问题是：**这种情况下3个月后证书到期后自动续期是不是会失败？**
（我怀疑我昨天的重启后一直证书申请失败是这个原因，今天重新按上述步骤走了一遍就正常了，即证书续期的时候80和443都不可用？）

如果是的话，是不是作者支持DNS挑战的方式更好？
