### ISSUE TITLE
ACL规则跳本地socks5的warp代理后无法走IPv6

### ISSUE THREAD

**Issue by toyo2333** [apernet/hysteria#892]
VPS的ip本身无法使用chagpt，于是用xray做了了一个warp，本身xray也在用。然后做成s5给hy2也用

配置是这样的
```
listen: :443

acl:
  inline: 
    - reject(all, udp/443)
    - reject(geoip:cn)
    - xray_warp(suffix:ai.com)
    - xray_warp(suffix:auth0.com)
    - xray_warp(suffix:challenges.cloudflare.com)
    - xray_warp(suffix:client-api.arkoselabs.com) 
    - xray_warp(suffix:events.statsigapi.net)
    - xray_warp(suffix:featuregates.org)
    - xray_warp(suffix:identrust.com)
    - xray_warp(suffix:intercom.io)
    - xray_warp(suffix:intercomcdn.com)
    - xray_warp(suffix:openai.com)
    - xray_warp(suffix:openaiapi-site.azureedge.net)
    - xray_warp(suffix:sentry.io)
    - xray_warp(suffix:stripe.com)
    - xray_warp(suffix:oaistatic.com)
    - xray_warp(suffix:oaiusercontent.com)
    - direct(all)


outbounds:
  - name: xray_warp
    type: socks5
    socks5:
      addr: xray:40000
```
上面的这个xray:40000是xray暴露出来使用的warp出站代理（warp配置了双栈）。

xray那边的warp出站设置的是ipv6出站。走xray代理后，使用的Cloudflare的ipv6地址（https://chat.openai.com/cdn-cgi/trace ) 这个地址可以看出站ip，可以成功解锁GPT

但是走hy2后，上述地址看到的是确实走了warp出站，但是走的是CF的ipv4地址（这个地址不能解锁gpt）。

我想问问是哪里配置的问题导致的？ 还是说我这种用法，目前不支持。

另外还有一个问题就是
- reject(all, udp/443) 这个是搬xray那边的规则的目的是不代理quic流量。我想问问这个在hy2这边是否有必要或者是否适用？
