### ISSUE TITLE
Docker 部署是否可以不依赖 host network？

### ISSUE THREAD

**Issue by e7h4n** [apernet/hysteria#901]
**你的功能请求是否与某个问题有关？**
我现在有一套成功运气起来的 hysteria server，配置如下:
```yaml
  hysteria:
    image: tobyxdd/hysteria
    restart: always
    network_mode: "host"
    volumes:
      - letsencrypt_data:/etc/letsencrypt/:ro
      - ./hysteria:/etc/hysteria/:ro
    command: ["server", "-c", "/etc/hysteria/config.yaml"]
```
```yaml
tls:
  cert: ...
  key: ...

auth:
  type: password
  password: ...
```

我遇到的问题是这个 service 要使用 host network，这导致在 acl 等配置中，不能直接使用 docker 网络中的其他 container name 作为 acl 的转发目标。

**描述你希望的解决方案**
我希望能避免 hysteria 使用 host network，而是使用 docker 的 bridge network，通过 ports 对外暴露端口，例如:
```yaml
  hysteria:
    image: tobyxdd/hysteria
    ports:
        - 443:443
    ...
```
但是在这么使用的过程中，发现客户端无法连接到服务端。我用的客户端是 surge，surge 提示代理不可用。服务端没有任何日志出现。

**有没有其他替代方案**
暂时没想到

**额外信息**
暂时没想到
