### ISSUE TITLE
求助双栈VPS，无法走V6出站

### ISSUE THREAD

**Issue by toyo2333** [apernet/hysteria#902]
VPS上执行：curl https://ip6.me/api/ 和 curl https://chat.openai.com/cdn-cgi/trace 得到的是 都是IPv6的地址，代表机器本身IPv6出站成功。

但是Hy2配置后走代理，从浏览器里访问上述地址，都是IPv4地址。

出站配置没有什么特殊的：
```
acl:
  inline: 
    - reject(all, udp/443)
    - reject(geoip:cn)
    - xray_warp(suffix:test-ipv6.com)
    - xray_warp(suffix:ai.com)
    - xray_warp(suffix:auth0.com)
    - xray_warp(suffix:challenges.cloudflare.com)
    - xray_warp(suffix:client-api.arkoselabs.com) 
    - xray_warp(suffix:events.statsigapi.net)
    - xray_warp(suffix:featuregates.org)
    - xray_warp(suffix:identrust.com)
    - xray_warp(suffix:intercom.io)
    - xray_warp(suffix:intercomcdn.com)
    - xray_warp(suffix:openai.com)
    - xray_warp(suffix:openaiapi-site.azureedge.net)
    - xray_warp(suffix:sentry.io)
    - xray_warp(suffix:stripe.com)
    - xray_warp(suffix:oaistatic.com)
    - xray_warp(suffix:oaiusercontent.com)
    - xray_warp(geosite:twitter)
    - xray_warp(geosite:reddit)
    - direct(all)


outbounds:
  - name: xray_warp
    type: socks5
    socks5:
      addr: xray:40000
``` 

相当于走direct出去只能走了ipv4，xray_warp这是本机xray上配的一个warpIPv6出站，是可以用warp的ipv6出去的。

说明，我的Xray默认配置也只能ipv4出去。所以我想是不是vps哪里配置的问题？但vps没问题啊，因为VPS上执行：curl https://ip6.me/api/ 和 curl https://chat.openai.com/cdn-cgi/trace 得到的是 都是IPv6的地址。

很困惑，求解答。

**Comment by toyo2333** [comment]
我配置了一个v6优先的出站，路由ip6.me走这个出去。
```
  - name: direct_v6
    type: direct
    direct:
      mode: 64
``` 

结果

ERROR   TCP error       {"addr": "xxxx:xxxxx", "id": "user", "reqAddr": "ip6.me:443", "error": "dial tcp6 [xxxx:xxxx:x:x::xx]:443: connect: cannot assign requested address"}

配置成auto就正常打开，但还是v4地址。

**Comment by toyo2333** [comment]
```yaml
listen: :443

acme:
    domains:
        - xxxx
    email: xxxx

auth:
    type: password
    password: xxxx
  
masquerade:
    type: proxy
    proxy:
        url: https://xxxx.com
        rewriteHost: true
acl:
  inline: 
    - reject(all, udp/443)
    - xray_warp(geosite:reddit)
    - direct(all)

outbounds:
  - name: xray_warp
    type: socks5
    socks5:
      addr: xray:40000
```
