### ISSUE TITLE
无法验证伪装效果

### ISSUE THREAD

**Issue by toyo2333** [apernet/hysteria#903]
```
masquerade:
    type: proxy
    proxy:
        url: https://bing.com
        rewriteHost: true
```

伪装使用的是反代bing.com，配置里使用的域名: hy.xxx.com 用了几个月，代理功能都正常，文档里看到可以验证，就想试一试。

按文档里提供的方法 无效,页面打不开

```
可以通过特定参数启动 Chrome 以强制使用 QUIC，测试你的伪装配置：

chrome --origin-to-force-quic-on=hy.xxx.com:443 
注意： 在用参数启动 Chrome 之前，请先确保完全退出了 Chrome，没有任何 Chrome 进程还在后台运行。否则参数可能不会生效。

然后访问 https://hy.xxx.com 验证伪装是否生效。
```
日志显示
```
2024-01-17T14:30:55Z    ERROR   TCP error       {"addr": "my-client-ip-address:port", "id": "user", "reqAddr": "hy.xxx.com:443", "error": "dial tcp4 my-VPS-ip-address:443: connect: connection refused"}
```

想问问是哪里配置不对么？这是伪装没生效么？还有其他验证方式么？
