### ISSUE TITLE
【Feature Request】服务端支持基于规则的TCP/HTTP转发

### ISSUE THREAD

**Issue by bobwng** [apernet/hysteria#931]
**你的功能请求是否与某个问题有关？**

目前很多VPS中不仅仅跑了hysteria服务，还有一些其他基于HTTP/HTTPS的服务。当同时部署hysteria和这些服务，不能共用同一个port作为entrypoint。这样的话，443端口只能被hysteria占用或只能被其他HTTP/HTTPS服务占用。

考虑/尝试过以下做法：

1. 使用traefik作为前端
    - 基于[CDN](https://v2.hysteria.network/zh/docs/misc/CDN/)的说明、#872 的讨论、以及我自己的尝试，没有办法使用traefik作为前端，使用TCP转发的方式将hysteria作为后端。
3. 使用hysteria作为前端
    - 目前的hysertia的TCP转发基于指定端口，这样还是需要多个端口才能让其他HTTP服务（如traefik）与hystertia同时运行在一台VPS上。
    - 从文档中来看， [伪装模式](https://v2.hysteria.network/zh/docs/advanced/Full-Server-Config/#httphttps)只能支持指定端口或者指定域名。这样的话，如果有多个域名运行在后端，应当也是不可以的。

**描述你希望的解决方案**

希望hysteria的服务端能支持基于规则的多协议转发服务，至少先支持基于规则HTTP/TCP转发。

例如，是否可以参考traefik的[TCP Router](https://doc.traefik.io/traefik/routing/routers/)，在hysteria的服务端配置文件中增加以下内容：

```yaml
tcpForwarding:
  - rule: "HostSNI(`traefik.example.com`)"
    tls:
      passthrough: true
    remote:
      - traefik-1.internal.example.com:8443
      - traefik-2.internal.example.com:8443
  - rule: "HostSNI(`*.sub-domain.example.com`)"
    tls:
      passthrough: true
    remote:
      - node-1.internal.sub-domain.example.com:443
      - node-2.internal.sub-domain.example.com:443
```

这样，当接收到域名为“traefik.example.com”或者为泛域名“*.sub-domain.example.com”的请求时，将请求内容不做更改（passthrough: true）分别转发到指定的远端服务器例如“traefik-1.internal.example.com:8443”或“node-2.internal.sub-domain.example.com:443”

**有没有其他替代方案**

**额外信息**
