### ISSUE TITLE
若不配置IP地址，hysteria默认不监听IPv4端口

### ISSUE THREAD

**Issue by lzm0** [apernet/hysteria#943]
配置如下：
```yaml
listen: :443

acme:
  domains:
    - example.com
  email: me@example.com

auth:
  type: password
  password: ********

masquerade:
  type: proxy
  proxy:
    url: https://news.ycombinator.com/
    rewriteHost: true
```

如果列出被监听的UDP端口，则只有IPv6
```bash
$ netstat -n --udp --listen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
udp        0      0 127.0.0.53:53           0.0.0.0:*                              
udp6       0      0 :::443                  :::*                       
```

若想监听IPv4，则必须将`listen`设为`0.0.0.0:443`.
