### ISSUE TITLE
One client - multiple servers?

### ISSUE THREAD

**Issue by Null-Kelvin** [apernet/hysteria#960]
I have multiple VPS with hysteria servers on them. But if I want to use all of them at once, I need to start multiple hysteria clients, which is inconvenient when it's more than three of them. Can one hysteria-client connect to multiple servers and set unique port to each one? Something like:

``` yaml
server_01: example.com:12345
auth: server_pass_01
socks5:
  listen: 0.0.0.0:1081 

server_02: another.example.com:54321
auth: server_pass_02
socks5:
  listen: 0.0.0.0:1082 
```
