### ISSUE TITLE
IPv6 reqAddr not connecting 

### ISSUE THREAD

**Issue by ShahryarShabani** [apernet/hysteria#962]
**Describe the bug**
whenever request addresses are IPv6s get rejected or can not be resolved 

**Client Apps**
Streisand
Nekobox

**Logs**
```
Mar 01 11:43:08 vps hysteria[157351]: 2024-03-01T11:43:08+03:30        ERROR        TCP error        {"addr": "****:36710", "id": "shahryar", "reqAddr": "[2a03:2880:f216:c6:face:b00c:0:7260]:80", "error": "dial tcp6 [2a03:2880:f216:c6:face:b00c:0:7260]:80: connect: network is unreachable"}

Mar 01 11:43:09 vps hysteria[157351]: 2024-03-01T11:43:09+03:30        ERROR        TCP error        {"addr": "****:36710", "id": "shahryar", "reqAddr": "[2a03:2880:f201:c6:face:b00c:0:7260]:443", "error": "dial tcp6 [2a03:2880:f201:c6:face:b00c:0:7260]:443: connect: network is unreachable"}
```

**Device and Operating System**
Ubuntu 20.04

**Server Config**
```yaml
listen: :443
tls:
  cert: /etc/hysteria/ca.crt
  key: /etc/hysteria/ca.key
quic:
  initStreamReceiveWindow: 26843545
  maxStreamReceiveWindow: 26843545
  initConnReceiveWindow: 67108864
  maxConnReceiveWindow: 67108864
  maxIdleTimeout: 4s
  keepAlivePeriod: 4s
  maxIncomingStreams: 1024
  disablePathMTUDiscovery: false
auth:
  type: userpass
  userpass:
    shahryar: enn1hErZ4bB83w1
masquerade:
  type: proxy
  proxy:
    url: https://abadis.ir/
    rewriteHost: true
resolver:
  type: tcp
  tcp:
    addr: 8.8.8.8:53
    timeout: 4s
  udp:
    addr: 8.8.4.4:53
    timeout: 4s
  tls:
    addr: 1.1.1.1:853
    timeout: 10s
    sni: cloudflare-dns.com
    insecure: true
  https:
    addr: 1.1.1.1:443
    timeout: 10s
    sni: cloudflare-dns.com
    insecure: true
disableUDP: false
ignoreClientBandwidth: true
udpIdleTimeout: 120s
acl:
  inline:
    - reject(all, udp/443)
    - reject(geosite:ir)
    - reject(geoip:ir)
    - reject(geosite:category-ads-all)
    - reject(geoip:private)
    - direct(geoip:facebook)
    - warp(geoip:google)
    - warp(geosite:netflix)
    - warp(35.184.0.0/13)
    - warp(geosite:spotify)
    - warp(geosite:google)
    - warp(geosite:openai)
    - warp(geoip:openai)
    - direct(all)
  geoip: /etc/hysteria/geoip.dat
  geosite: /etc/hysteria/geosite.dat
outbounds:
  - name: warp
    type: socks5
    socks5:
      addr: 127.0.0.1:40000
trafficStats:
  listen: :9000
obfs:
  type: salamander
  salamander:
    password: VbDcrcJzytZ4
```
