### ISSUE TITLE
如何配置hysteria2的ACL; How to configure the ACL of hysteria2?

### ISSUE THREAD

**Issue by HeInfinity** [apernet/hysteria#967]
我按照官方文档配置了config.yaml后, 发现要么只能使用direct, 要么只能使用proxy, 请问我应该如何正确配置acl?
After I configured config.yaml according to the official documentation, I found that either direct or proxy can only be used. How should I configure acl correctly?

```yaml
outbounds:
  - name: ipv4_only
    type: direct
    direct: 
      mode: 4
  - name: proxy
    type: socks5
    socks5:
      addr: 192.168.1.1
      username: username
      password: password

acl: #第一种配置方式, the first way
  inline: 
    - ipv4_only(geosite:google)
    - ipv4_only(geosite:youtube)
    - socks(all)
  
acl: #第二种配置方式, the second way
  inline: 
    - proxy(geosite:netflix)
    - direct(all)
```

outbounds是固定的没有改变, 只是acl的配置方式有不同, 两种方式我都无法得到想要的结果. 应该如何配置呢?
Outbounds is fixed and has not changed, but the configuration method of acl is different. I can't get the desired result with both methods. How should I configure it?

期待回复!谢谢!
Looking forward to your early and positive reply!
