### ISSUE TITLE
hy2 ipv6的解析问题

### ISSUE THREAD

**Issue by ypxun** [apernet/hysteria#968]
首先抱歉，对于将要说的问题，我自己觉得很晕，不知道属不属于hy2，不是的话莫怪。<br>
我服务端：vmess+ws的节点，客户端：clash-nyanpasu，mihomo核。在[ip125.com](https://ip125.com)上检测，会显示vps的两个ip，一个v4，一个v6（主用于google）。这是我希望的结果，因为我vps在韩国，作用于google的ipv6可以突破韩国的年龄限制。<br>
但服务端搭：hy2的节点，客户端：clash-nyanpasu，mihomo核。在[ip125.com](https://ip125.com)上检测，只会显示vps的一个ipv4地址。这不符合我的预期，此时google的搜索结果有年龄限制。<br>
客户端的配置文件同时包含vmess和hy2节点，分流和dns解析是相同的，同时我是使用clash的tun模式。
服务端和客户端的配置我贴下：
```
# 服务端 debian 11
listen: :10000 #监听端口

#使用自签证书
tls:
  cert: /etc/hysteria/server.crt
  key: /etc/hysteria/server.key

auth:
  type: password
  password: 
  
masquerade:
  type: proxy
  proxy:
    url: https://bing.com #伪装网址
    rewriteHost: true

quic:
  initStreamReceiveWindow: 8388608 
  maxStreamReceiveWindow: 8388608 
  initConnReceiveWindow: 20971520 
  maxConnReceiveWindow: 20971520 
  maxIdleTimeout: 30s 
  maxIncomingStreams: 1024 
  disablePathMTUDiscovery: false
```
```
# 客户端：win11 clash-nyanpasu 1.5.0 内核 mihomo alpha-d273408
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: silent
external-controller: 127.0.0.1:9090

dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  nameserver:
  - https://8.8.8.8/dns-query
  - https://1.1.1.1/dns-query
  nameserver-policy:
    'geosite:cn': 
    - https://223.5.5.5/dns-query
    - https://doh.pub/dns-query

profile:
  tracing: true

proxy-providers:
  节点:
    type: http
    path: ./Proxy/节点.yml
    url: xxx
    interval: 10800
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 6

  Hysteria2:
    type: file
    path: ./Proxy/Hysteria2.yml

其他省略
```
```
# Hysteria2.yml
proxies:
  - name: Hysteria2
    type: hysteria2
    server: 服务器ipv4地址
    port: 10000
    #  up和down均不写或为0则使用BBR流控
    up: "30 Mbps" # 若不写单位，默认为 Mbps
    down: "1000 Mbps" # 若不写单位，默认为 Mbps
    password: 
    sni: https://bing.com #自签的话改为bing.com
    skip-cert-verify: true  #自签的话改为true

```
我现在就想搞清楚，这是搭的hy2节点有问题，还是clash这边的问题？
