### ISSUE TITLE
似乎 TCP 和 UDP 转发 客户端配置不支持填入 IPv6 地址

### ISSUE THREAD

**Issue by 5t-RawBeRry** [apernet/hysteria#969]
**描述问题**
当hy2作为客户端时，tcpForwarding 和 udpForwarding 的 listen 和 remote 均无法填写 IPv6 地址

**配置文件**
```yaml
server: xxx.xxx:443

auth: xxx

tcpForwarding:
  - listen: [::]:23333
    remote: [对端v6]:23333

udpForwarding:
  - listen: [::]:11451
    remote: [对端v6]:11451
    timeout: 20s
```

**预期行为**
可能是我写法问题，如果支持的话，可以在文档注明写法吗？

**日志**
如下类似报错
```log
2024-03-10T01:40:09Z    INFO    client mode
2024-03-10T01:40:09Z    FATAL   failed to read client config    {"error": "While parsing config: yaml: line 5: did not find expected node content"}
```

**设备和操作系统**
x86_64 设备
Debian 12 系统

**额外信息**
无

**Comment by haruue** [comment]
☝️ 这就是 YAML

```yaml
tcpForwarding:
  - listen: "[::]:23333"   # <- 加上双引号
    remote: "[对端v6]:23333"
```
