### ISSUE TITLE
Routing by users

### ISSUE THREAD

**Issue by gorbesiah** [apernet/hysteria#992]
Hi there
I want to add 3 or more users and but i didn't find any user config example.
is this config OK?
and is it possible to route each user to specific outbound?

**ServerConfig**

```
listen: :10000
tls:
  cert: /root/hy2/ca.crt
  key: /root/hy2/ca.key
obfs:
  type: salamander
  salamander:
    password: Ra5L69KvT6zw6si
auth:
  type: password
  password: bQ5x72xq4H94Lb
  userpass: 
    user1: 123456
    user2: 654321
    user3: 635241
quic:
  initStreamReceiveWindow: 8388608
  maxStreamReceiveWindow: 8388608
  initConnReceiveWindow: 20971520
  maxConnReceiveWindow: 20971520
  maxIdleTimeout: 60s
  maxIncomingStreams: 1024
  disablePathMTUDiscovery: false
bandwidth:
  up: 1 gbps
  down: 1 gbps
ignoreClientBandwidth: false
disableUDP: false
udpIdleTimeout: 60s
outbounds:
  - name: sproxy
    type: socks5
    socks5:
      addr: 127.0.0.1:1356
resolver:
  type: udp
  tcp:
    addr: 8.8.8.8:53
    timeout: 4s
  udp:
    addr: 8.8.4.4:53
    timeout: 4s
  tls:
    addr: 1.1.1.1:853
    timeout: 10s
    sni: cloudflare-dns.com
    insecure: false
  https:
    addr: 1.1.1.1:443
    timeout: 10s
    sni: cloudflare-dns.com
    insecure: false

``` 

USER1 Config:

```
server: 158.78.192.157:10000
auth: bQ5x72xq4H94Lb
 userpass:
 user1: 123456
transport:
  type: udp
  udp:
    hopInterval: 30s
obfs:
  type: salamander
  salamander:
    password: Ra5L69KvT6zw6si
tls:
  sni: google.com 
  insecure: true 
bandwidth: 
  up: 20 mbps
  down: 100 mbps
quic:
  initStreamReceiveWindow: 8388608 
  maxStreamReceiveWindow: 8388608 
  initConnReceiveWindow: 20971520 
  maxConnReceiveWindow: 20971520 
  maxIdleTimeout: 30s 
  keepAlivePeriod: 10s 
  disablePathMTUDiscovery: false
fastOpen: true
lazy: true
socks5:
  listen: 127.0.0.1:10808
http:
  listen: 127.0.0.1:10809
```
